//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAG_DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANCOS
    {
        public short BANCO { get; set; }
        public string SIGLA_BANCO { get; set; }
        public string DESC_BANCO { get; set; }
        public string TIPO_BANCO { get; set; }
        public string API_ESTADO { get; set; }
        public string API_TRANSACCION { get; set; }
        public string USU_CRE { get; set; }
        public System.DateTime FEC_CRE { get; set; }
        public string USU_MOD { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
        public string CUENTA_ENCAJE { get; set; }
        public string RECIPIENTE_ID { get; set; }
        public string CONECTADO_SIAFI { get; set; }
        public string HABILITADO_ENVIOS { get; set; }
        public string BEN_PAIS_ID { get; set; }
        public string BEN_TIPO_ID { get; set; }
        public string BEN_NRO_ID { get; set; }
        public Nullable<short> BEN_BANCO { get; set; }
        public string BEN_CUENTA { get; set; }
    }
}
