//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAG_DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUENTAS_BANCARIAS
    {
        public CUENTAS_BANCARIAS()
        {
            this.CUENTAS_BANCARIAS1 = new HashSet<CUENTAS_BANCARIAS>();
            this.LIBROS_BANCO = new HashSet<LIBROS_BANCO>();
        }
    
        public short BANCO { get; set; }
        public string CUENTA { get; set; }
        public string DESC_CUENTA { get; set; }
        public string TIPO_CUENTA { get; set; }
        public string MONEDA { get; set; }
        public Nullable<short> BANCO_BCH { get; set; }
        public string CUENTA_BCH { get; set; }
        public string TIPO_CTA_PROYECTO { get; set; }
        public string API_ESTADO { get; set; }
        public string API_TRANSACCION { get; set; }
        public string USU_CRE { get; set; }
        public System.DateTime FEC_CRE { get; set; }
        public string USU_MOD { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
    
        public virtual ICollection<CUENTAS_BANCARIAS> CUENTAS_BANCARIAS1 { get; set; }
        public virtual CUENTAS_BANCARIAS CUENTAS_BANCARIAS2 { get; set; }
        public virtual MONEDAS MONEDAS { get; set; }
        public virtual ICollection<LIBROS_BANCO> LIBROS_BANCO { get; set; }
    }
}
