//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAG_DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DCO_DOCUMENTOS
    {
        public DCO_DOCUMENTOS()
        {
            this.DCO_DOCUMENTOS_COLUMNAS = new HashSet<DCO_DOCUMENTOS_COLUMNAS>();
            this.DTP_DOCUMENTOS_DET = new HashSet<DTP_DOCUMENTOS_DET>();
            this.TPR_DOCUMENTOS = new HashSet<TPR_DOCUMENTOS>();
        }
    
        public string ID_DOCUMENTO { get; set; }
        public string DESC_DOCUMENTO { get; set; }
        public string API_ESTADO { get; set; }
        public string API_TRANSACCION { get; set; }
        public string USU_CRE { get; set; }
        public System.DateTime FEC_CRE { get; set; }
        public string USU_MOD { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
    
        public virtual ICollection<DCO_DOCUMENTOS_COLUMNAS> DCO_DOCUMENTOS_COLUMNAS { get; set; }
        public virtual ICollection<DTP_DOCUMENTOS_DET> DTP_DOCUMENTOS_DET { get; set; }
        public virtual ICollection<TPR_DOCUMENTOS> TPR_DOCUMENTOS { get; set; }
    }
}
