//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAG_DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DCO_DOCUMENTOS_COLUMNAS
    {
        public DCO_DOCUMENTOS_COLUMNAS()
        {
            this.DTP_DETALLES_DET = new HashSet<DTP_DETALLES_DET>();
            this.TPR_DETALLES = new HashSet<TPR_DETALLES>();
        }
    
        public string ID_DOCUMENTO { get; set; }
        public short ID_COLUMNA { get; set; }
        public string ESPECIAL { get; set; }
        public string API_ESTADO { get; set; }
        public string API_TRANSACCION { get; set; }
        public string USU_CRE { get; set; }
        public System.DateTime FEC_CRE { get; set; }
        public string USU_MOD { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
    
        public virtual DCO_COLUMNAS DCO_COLUMNAS { get; set; }
        public virtual DCO_DOCUMENTOS DCO_DOCUMENTOS { get; set; }
        public virtual ICollection<DTP_DETALLES_DET> DTP_DETALLES_DET { get; set; }
        public virtual ICollection<TPR_DETALLES> TPR_DETALLES { get; set; }
    }
}
