//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAG_DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEDUCCIONES
    {
        public short DEDUCCION { get; set; }
        public short TIPO { get; set; }
        public short SUB_TIPO { get; set; }
        public string DESCRIPCION { get; set; }
        public string BASE_LEY { get; set; }
        public string PRIORIDAD { get; set; }
        public string BASE_CALCULO { get; set; }
        public string MODO_CALCULO { get; set; }
        public string API_ESTADO { get; set; }
        public string API_TRANSACCION { get; set; }
        public string USU_CRE { get; set; }
        public Nullable<System.DateTime> FEC_CRE { get; set; }
        public string USU_MOD { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
        public Nullable<decimal> MONTO_PORC { get; set; }
        public Nullable<decimal> MONTO_FIJO { get; set; }
        public string NETEABLE { get; set; }
        public string VIGENTE { get; set; }
    }
}
