//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAG_DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLB_LIB_BOLSON_DET
    {
        public short GESTION { get; set; }
        public short INSTITUCION { get; set; }
        public short GA { get; set; }
        public short NRO_DOCUMENTO { get; set; }
        public short SECUENCIA { get; set; }
        public short PAG_INSTITUCION { get; set; }
        public short PAG_GA { get; set; }
        public short LIB_GESTION { get; set; }
        public short LIB_BANCO { get; set; }
        public string LIB_CUENTA { get; set; }
        public string LIB_LIBRETA { get; set; }
        public string MONEDA { get; set; }
        public short FUENTE { get; set; }
        public string API_ESTADO { get; set; }
        public string API_TRANSACCION { get; set; }
        public string USU_CRE { get; set; }
        public System.DateTime FEC_CRE { get; set; }
        public string USU_MOD { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
    
        public virtual DLB_LIB_BOLSON_CAB DLB_LIB_BOLSON_CAB { get; set; }
        public virtual FUENTES_FINANCIAMIENTO FUENTES_FINANCIAMIENTO { get; set; }
        public virtual GERENCIAS_ADMINISTRATIVAS GERENCIAS_ADMINISTRATIVAS { get; set; }
        public virtual LIBRETAS LIBRETAS { get; set; }
        public virtual MONEDAS MONEDAS { get; set; }
    }
}
