//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAG_DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTP_TIPOS_PROGRA_CAB
    {
        public DTP_TIPOS_PROGRA_CAB()
        {
            this.DTP_TIPOS_PROGRA_DET = new HashSet<DTP_TIPOS_PROGRA_DET>();
        }
    
        public short GESTION { get; set; }
        public short INSTITUCION { get; set; }
        public short GA { get; set; }
        public short NRO_DOCUMENTO { get; set; }
        public short DPTO_LUGAR { get; set; }
        public short MUN_LUGAR { get; set; }
        public string TIPO_OPERACION { get; set; }
        public string USU_VERIFICACION { get; set; }
        public Nullable<System.DateTime> FEC_VERIFICACION { get; set; }
        public string USU_APROBACION { get; set; }
        public Nullable<System.DateTime> FEC_APROBACION { get; set; }
        public string API_ESTADO { get; set; }
        public string API_TRANSACCION { get; set; }
        public string USU_CRE { get; set; }
        public System.DateTime FEC_CRE { get; set; }
        public string USU_MOD { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
    
        public virtual GERENCIAS_ADMINISTRATIVAS GERENCIAS_ADMINISTRATIVAS { get; set; }
        public virtual MUNICIPIOS MUNICIPIOS { get; set; }
        public virtual ICollection<DTP_TIPOS_PROGRA_DET> DTP_TIPOS_PROGRA_DET { get; set; }
    }
}
