//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAG_DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUENTES_FINANCIAMIENTO
    {
        public FUENTES_FINANCIAMIENTO()
        {
            this.DOCUMENTOS_DE_GASTOS = new HashSet<DOCUMENTOS_DE_GASTOS>();
            this.DLB_LIB_BOLSON_DET = new HashSet<DLB_LIB_BOLSON_DET>();
            this.PRG_LIBRETAS_BOLSON = new HashSet<PRG_LIBRETAS_BOLSON>();
            this.LIBRETAS = new HashSet<LIBRETAS>();
        }
    
        public short FUENTE { get; set; }
        public short GRUPO_FUENTE { get; set; }
        public short SUB_GRUPO_FUENTE { get; set; }
        public string DESC_FUENTE { get; set; }
        public string VIGENTE { get; set; }
        public string API_ESTADO { get; set; }
        public string API_TRANSACCION { get; set; }
        public string USU_CRE { get; set; }
        public Nullable<System.DateTime> FEC_CRE { get; set; }
        public string USU_MOD { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
    
        public virtual ICollection<DOCUMENTOS_DE_GASTOS> DOCUMENTOS_DE_GASTOS { get; set; }
        public virtual ICollection<DLB_LIB_BOLSON_DET> DLB_LIB_BOLSON_DET { get; set; }
        public virtual ICollection<PRG_LIBRETAS_BOLSON> PRG_LIBRETAS_BOLSON { get; set; }
        public virtual ICollection<LIBRETAS> LIBRETAS { get; set; }
    }
}
