//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAG_DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class GERENCIAS_ADMINISTRATIVAS
    {
        public GERENCIAS_ADMINISTRATIVAS()
        {
            this.DLB_LIB_BOLSON_CAB = new HashSet<DLB_LIB_BOLSON_CAB>();
            this.DLB_LIB_BOLSON_DET = new HashSet<DLB_LIB_BOLSON_DET>();
            this.DTP_TIPOS_PROGRA_CAB = new HashSet<DTP_TIPOS_PROGRA_CAB>();
            this.PRG_LIBRETAS_BOLSON = new HashSet<PRG_LIBRETAS_BOLSON>();
            this.LIBROS_BANCO = new HashSet<LIBROS_BANCO>();
            this.LIBRETAS = new HashSet<LIBRETAS>();
        }
    
        public short GESTION { get; set; }
        public short INSTITUCION { get; set; }
        public short GA { get; set; }
        public string DESC_GA { get; set; }
        public string TIPO_GA { get; set; }
        public short ETAPA_DOCUMENTO { get; set; }
        public string VIGENTE { get; set; }
        public string API_ESTADO { get; set; }
        public string API_TRANSACCION { get; set; }
        public string USU_CRE { get; set; }
        public System.DateTime FEC_CRE { get; set; }
        public string USU_MOD { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
    
        public virtual ICollection<DLB_LIB_BOLSON_CAB> DLB_LIB_BOLSON_CAB { get; set; }
        public virtual ICollection<DLB_LIB_BOLSON_DET> DLB_LIB_BOLSON_DET { get; set; }
        public virtual ICollection<DTP_TIPOS_PROGRA_CAB> DTP_TIPOS_PROGRA_CAB { get; set; }
        public virtual ICollection<PRG_LIBRETAS_BOLSON> PRG_LIBRETAS_BOLSON { get; set; }
        public virtual ICollection<LIBROS_BANCO> LIBROS_BANCO { get; set; }
        public virtual ICollection<LIBRETAS> LIBRETAS { get; set; }
    }
}
