//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAG_DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIBROS_BANCO
    {
        public LIBROS_BANCO()
        {
            this.LIBRETAS = new HashSet<LIBRETAS>();
        }
    
        public short GESTION { get; set; }
        public short BANCO { get; set; }
        public string CUENTA { get; set; }
        public string MONEDA { get; set; }
        public string TIPO_CUENTA { get; set; }
        public string CUENTA_CONTABLE { get; set; }
        public Nullable<decimal> SALDO_INICIAL { get; set; }
        public decimal SALDO { get; set; }
        public short INSTITUCION { get; set; }
        public short GA { get; set; }
        public string UTILIZA_LIBRETAS { get; set; }
        public string SE_CONCILIA { get; set; }
        public string DEBITA_POR { get; set; }
        public string ACREDITA_POR { get; set; }
        public string API_ESTADO { get; set; }
        public string API_TRANSACCION { get; set; }
        public string USU_CRE { get; set; }
        public System.DateTime FEC_CRE { get; set; }
        public string USU_MOD { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
    
        public virtual GERENCIAS_ADMINISTRATIVAS GERENCIAS_ADMINISTRATIVAS { get; set; }
        public virtual ICollection<LIBRETAS> LIBRETAS { get; set; }
        public virtual MONEDAS MONEDAS { get; set; }
        public virtual CUENTAS_BANCARIAS CUENTAS_BANCARIAS { get; set; }
    }
}
