//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAG_DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUNICIPIOS
    {
        public MUNICIPIOS()
        {
            this.DOCUMENTOS_DE_GASTOS = new HashSet<DOCUMENTOS_DE_GASTOS>();
            this.DLB_LIB_BOLSON_CAB = new HashSet<DLB_LIB_BOLSON_CAB>();
            this.DTP_TIPOS_PROGRA_CAB = new HashSet<DTP_TIPOS_PROGRA_CAB>();
        }
    
        public short DEPARTAMENTO { get; set; }
        public short MUNICIPIO { get; set; }
        public string DESC_MUNICIPIO { get; set; }
        public string SIGLA_MUNICIPIO { get; set; }
        public string VIGENTE { get; set; }
        public string API_ESTADO { get; set; }
        public string API_TRANSACCION { get; set; }
        public string USU_CRE { get; set; }
        public Nullable<System.DateTime> FEC_CRE { get; set; }
        public string USU_MOD { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
    
        public virtual ICollection<DOCUMENTOS_DE_GASTOS> DOCUMENTOS_DE_GASTOS { get; set; }
        public virtual ICollection<DLB_LIB_BOLSON_CAB> DLB_LIB_BOLSON_CAB { get; set; }
        public virtual ICollection<DTP_TIPOS_PROGRA_CAB> DTP_TIPOS_PROGRA_CAB { get; set; }
    }
}
