//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAG_DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBJETOS_DEL_GASTO
    {
        public short GESTION { get; set; }
        public string OBJETO { get; set; }
        public short GRUPO_OBJETO { get; set; }
        public short SUB_GRUPO_OBJETO { get; set; }
        public short PARTIDA_OBJETO { get; set; }
        public short SUB_PARTIDA_OBJETO { get; set; }
        public string DESC_OBJETO { get; set; }
        public string IMPUTABLE { get; set; }
        public string VIGENTE { get; set; }
        public string API_ESTADO { get; set; }
        public string API_TRANSACCION { get; set; }
        public string USU_CRE { get; set; }
        public Nullable<System.DateTime> FEC_CRE { get; set; }
        public string USU_MOD { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
        public string NO_DISMINUYE_MPR { get; set; }
        public string NO_AUMENTA_MPR { get; set; }
        public string TRASLADO_INTEGRO_MPR { get; set; }
        public string INST_EXCEPCION_MPR { get; set; }
        public string NO_DISMINUYE_ERP { get; set; }
        public string NO_AUMENTA_ERP { get; set; }
        public string INST_EXCEPCION_ERP { get; set; }
    }
}
