//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAG_DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPR_TIPOS_PROGRAMACION
    {
        public TPR_TIPOS_PROGRAMACION()
        {
            this.TPR_DOCUMENTOS = new HashSet<TPR_DOCUMENTOS>();
        }
    
        public short INSTITUCION { get; set; }
        public short GA { get; set; }
        public short TIPO_PROGRAMACION { get; set; }
        public string DESC_TIPO_PROGRAMACION { get; set; }
        public string ESPECIAL { get; set; }
        public string API_ESTADO { get; set; }
        public string API_TRANSACCION { get; set; }
        public string USU_CRE { get; set; }
        public System.DateTime FEC_CRE { get; set; }
        public string USU_MOD { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
    
        public virtual ICollection<TPR_DOCUMENTOS> TPR_DOCUMENTOS { get; set; }
    }
}
