//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAG_DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class VM_PAG_LISTA_VALORES
    {
        public short ID_COLUMNA { get; set; }
        public string DESC_COLUMNA { get; set; }
        public string TABLA { get; set; }
        public string COLUMNA { get; set; }
        public string TIPO_VALOR { get; set; }
        public string VALOR { get; set; }
        public string DESCRIPCION { get; set; }
        public string OTROS_VALORES { get; set; }
        public decimal LLAVE_VIEW { get; set; }
    }
}
