//------------------------------------------------------------------------------
//                         Secretaria de Finanzas
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


namespace PAG_DTO
{
    
    
    public class DCO_COLUMNAS_DTO
    {
       [DisplayName("Id Columna")]//,MaxLength(4)]
        public System.Int16 ID_COLUMNA { get; set; }
       [DisplayName("Descripción")]//, DataType(DataType.MultilineText), MaxLength(200)]
        public System.String DESC_COLUMNA { get; set; }
       [DisplayName("Tipo Dato")]//, MaxLength(15)]
        public System.String TIPO_COLUMNA { get; set; }
       [DisplayName("Nombre Tabla")]//, MaxLength(30)]
        public System.String TABLA { get; set; }
       [DisplayName("Nombre Columna")]//, MaxLength(30)]
        public System.String COLUMNA { get; set; }
       [DisplayName("Tabla Origen")]//, MaxLength(30)]
        public string TABLA_ORIGEN { get; set; }
       [DisplayName("Columna Origen")]//, MaxLength(30)]
        public string COLUMNA_ORIGEN { get; set; }
       [DisplayName("Otros Valores")]//, MaxLength(200)]
        public string OTROS_VALORES { get; set; }
       [DisplayName("Tiene Lista de Valores")]//, MaxLength(1)]
        public string TIENE_LISTA { get; set; }
       [DisplayName("Estado")]//, MaxLength(20), ReadOnly(true)]
        public System.String API_ESTADO { get; set; }
       [DisplayName("Transacción")]//, MaxLength(20), Required(ErrorMessage = "La Transacción es obligatoria")]
        public System.String API_TRANSACCION { get; set; }
       [DisplayName("Creado por")]//, MaxLength(30), ReadOnly(true)]
        public System.String USU_CRE { get; set; }
       [DisplayName("Fecha Creación ")]//, ReadOnly(true)]
        public System.DateTime FEC_CRE { get; set; }
       [DisplayName("Modificado por")]//, MaxLength(30), ReadOnly(true)]
        public System.String USU_MOD { get; set; }
       [DisplayName("Fecha Modificación")]//, ReadOnly(true)]
        public System.DateTime? FEC_MOD { get; set; }
        
        public DCO_COLUMNAS_DTO()
        {
        }
    }
}
