//------------------------------------------------------------------------------
//                         Secretaria de Finanzas
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


namespace PAG_DTO
{
    
    
    public class DCO_DOCUMENTOS_COLUMNAS_DTO
    {

        [DisplayName("Id Columna")]//, MaxLength(4)]
        public System.Int16 ID_COLUMNA { get; set; }
        [DisplayName("ID documento")]//, MaxLength(10)]
        public System.String ID_DOCUMENTO { get; set; }
        //[UIHint("Bandera")]
        [DisplayName("Especial")]//, MaxLength(1)]
        public System.String ESPECIAL { get; set; }
        [DisplayName("Estado")]//, MaxLength(20), ReadOnly(true)]
        public System.String API_ESTADO { get; set; }
        [DisplayName("Transacción")]//, MaxLength(20), Required(ErrorMessage = "La Transacción es obligatoria")]
        public System.String API_TRANSACCION { get; set; }
        [DisplayName("Creado por")]//, MaxLength(30), ReadOnly(true)]
        public System.String USU_CRE { get; set; }
        [DisplayName("Fecha Creación ")]//, ReadOnly(true)]
        public System.DateTime FEC_CRE { get; set; }
        [DisplayName("Modificado por")]//, MaxLength(30), ReadOnly(true)]
        public System.String USU_MOD { get; set; }
        [DisplayName("Fecha Modificación")]//, ReadOnly(true)]
        public System.DateTime? FEC_MOD { get; set; }
        // Decripciones
        [DisplayName("Documento")]//, ReadOnly(true)]
        public System.String DESC_DOCUMENTO { get; set; }
        [DisplayName("Columna")]//, ReadOnly(true)]
        public System.String DESC_COLUMNA { get; set; }
        [DisplayName("Tipo")]//, ReadOnly(true)]
        public System.String TIPO_COLUMNA { get; set; }
        public DCO_DOCUMENTOS_COLUMNAS_DTO()
        {
        }
    }
}
