//------------------------------------------------------------------------------
//                         Secretaria de Finanzas
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


namespace PAG_DTO
{
    
    
    public class DLB_LIB_BOLSON_DET_DTO
    {

        [DisplayName("Gestión")]//, MaxLength(4)]
        public short GESTION { get; set; }
        [DisplayName("Institución")]//, MaxLength(4)]
        public short INSTITUCION { get; set; }
        [DisplayName("GA")]//, MaxLength(3)]
        public short GA { get; set; }
        [DisplayName("Nro. Documento")]//, MaxLength(5)]
        public short NRO_DOCUMENTO { get; set; }
        [DisplayName("Secuencia")]//, MaxLength(2)]
        public short SECUENCIA { get; set; }
        [DisplayName("Institución")]//, MaxLength(4)]
        public short PAG_INSTITUCION { get; set; }
        [DisplayName("GA")]//, MaxLength(3)]
        public short PAG_GA { get; set; }
        [DisplayName("Gestión")]//, MaxLength(4)]
        public short LIB_GESTION { get; set; }
        [DisplayName("Banco")]//, MaxLength(5)]
        public short LIB_BANCO { get; set; }
        [DisplayName("Cuenta")]//, MaxLength(20)]
        public System.String LIB_CUENTA { get; set; }
        [DisplayName("Libreta")]//, MaxLength(11)]
        public System.String LIB_LIBRETA { get; set; }
        [DisplayName("Moneda")]//, MaxLength(3)]
        public System.String MONEDA { get; set; }
        [DisplayName("Fuente")]//, MaxLength(2)]
        public short FUENTE { get; set; }
        [DisplayName("Estado")]//, MaxLength(20), ReadOnly(true)]
        public System.String API_ESTADO { get; set; }
        [DisplayName("Transacción")]//, MaxLength(20), Required(ErrorMessage = "La Transacción es obligatoria")]
        public System.String API_TRANSACCION { get; set; }
        [DisplayName("Creado por")]//, MaxLength(30), ReadOnly(true)]
        public System.String USU_CRE { get; set; }
        [DisplayName("Fecha Creación ")]//, ReadOnly(true)]
        public System.DateTime FEC_CRE { get; set; }
        [DisplayName("Modificado por")]//, MaxLength(30), ReadOnly(true)]
        public System.String USU_MOD { get; set; }
        [DisplayName("Fecha Modificación")]//, ReadOnly(true)]
        public System.DateTime? FEC_MOD { get; set; }

        [DisplayName("")]//, MaxLength(60), ReadOnly(true)]
        public System.String DESC_INSTITUCION { get; set; }

        [DisplayName("")]//, MaxLength(60), ReadOnly(true)]
        public System.String DESC_GA { get; set; }

        [DisplayName("")]//, MaxLength(60), ReadOnly(true)]
        public System.String DESC_FUENTE { get; set; }


        public DLB_LIB_BOLSON_DET_DTO()
        {
        }
    }
}
