//------------------------------------------------------------------------------
//                         Secretaria de Finanzas
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


namespace PAG_DTO
{
    
    
    public class DTP_DETALLES_DET_DTO
    {

        [DisplayName("Gestión")]//, MaxLength(4)]
        public short GESTION { get; set; }
        [DisplayName("Institución")]//, MaxLength(4)]
        public short INSTITUCION { get; set; }
        [DisplayName("GA")]//, MaxLength(3)]
        public short GA { get; set; }
        [DisplayName("Nro. Documento")]//, MaxLength(5)]
        public short NRO_DOCUMENTO { get; set; }
        [DisplayName("Institución")]//, MaxLength(4)]
        public short INSTITUCION_PROG { get; set; }
        [DisplayName("GA")]//, MaxLength(3)]
        public short GA_PROG { get; set; }
        [DisplayName("Tipo Programación")]//, MaxLength(4)]
        public short TIPO_PROGRAMACION { get; set; }
        [DisplayName("Sec.Documento")]//, MaxLength(3)]
        public short SECUENCIA_DOC { get; set; }
        [DisplayName("Sec.Detalle")]//, MaxLength(4)]
        public short SECUENCIA_DET { get; set; }
        [DisplayName("ID Documento")]//, MaxLength(1)]
        public System.String ID_DOCUMENTO { get; set; }
        [DisplayName("ID Columna")]//, MaxLength(4)]
        public short ID_COLUMNA { get; set; }
        [DisplayName("Valor Número")]//, MaxLength(38)]
        public Nullable<decimal> VALOR_NUMERO { get; set; }
        [DisplayName("Valor Cadena")]//, MaxLength(30)]
        public System.String VALOR_CADENA { get; set; }
        [DisplayName("Estado")]//, MaxLength(20), ReadOnly(true)]
        public System.String API_ESTADO { get; set; }
        [DisplayName("Transacción")]//, MaxLength(20), Required(ErrorMessage = "La Transacción es obligatoria")]
        public System.String API_TRANSACCION { get; set; }
        [DisplayName("Creado por")]//, MaxLength(30), ReadOnly(true)]
        public System.String USU_CRE { get; set; }
        [DisplayName("Fecha Creación ")]//, ReadOnly(true)]
        public System.DateTime FEC_CRE { get; set; }
        [DisplayName("Modificado por")]//, MaxLength(30), ReadOnly(true)]
        public System.String USU_MOD { get; set; }
        [DisplayName("Fecha Modificación")]//, ReadOnly(true)]
        public System.DateTime? FEC_MOD { get; set; }

        [DisplayName("Columna")]//, ReadOnly(true)]
        public System.String DESC_COLUMNA { get; set; }

        [DisplayName("Tipo")]//, ReadOnly(true)]
        public System.String TIPO_COLUMNA { get; set; }
        [DisplayName("Documento")]//, ReadOnly(true)]
        public System.String DESC_DOCUMENTO { get; set; }


        public DTP_DETALLES_DET_DTO()
        {
        }
    }
}
