//------------------------------------------------------------------------------
//                         Secretaria de Finanzas
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using PAG_DA;
using PAG_DTO;
using PAG_INTERFACES;
using PAG_MAPPERS;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Linq;
using System.ServiceModel;


namespace PAG_WCF
{
    
    
    public partial class PAG_Services : iPAG_Services
    {

        public List<DCO_COLUMNAS_DTO> qry_DCO_COLUMNAS_listado()
        {
            // TODO: Desarrolle su Codigo Aqui.
            return new DCO_COLUMNAS_RDN().DCO_COLUMNAS_listado();
        }

        public List<DCO_COLUMNAS_DTO> qry_DCO_COLUMNAS_filtrado(DCO_COLUMNAS_DTO precDto)
        {
            // TODO: Desarrolle su Codigo Aqui.
            return new DCO_COLUMNAS_RDN().DCO_COLUMNAS_filtrado(precDto);
        }

        public DCO_COLUMNAS_DTO ins_DCO_COLUMNAS_inserta(DCO_COLUMNAS_DTO precDto)
        {
            // TODO: Desarrolle su Codigo Aqui.
            return new DCO_COLUMNAS_RDN().DCO_COLUMNAS_inserta(precDto);
        }

        public DCO_COLUMNAS_DTO upd_DCO_COLUMNAS_actualiza(DCO_COLUMNAS_DTO precDto)
        {
            // TODO: Desarrolle su Codigo Aqui.
            return new DCO_COLUMNAS_RDN().DCO_COLUMNAS_actualiza(precDto);
        }

        public DCO_COLUMNAS_DTO del_DCO_COLUMNAS_elimina(params object[] pkeysDto)
        {
            // TODO: Desarrolle su Codigo Aqui.
            return new DCO_COLUMNAS_RDN().DCO_COLUMNAS_elimina(pkeysDto);
        }

    }
}
