//------------------------------------------------------------------------------
//                         Secretaria de Finanzas
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using PAG_DTO;
using PAG_INTERFACES;
using System.Collections.Generic;


namespace PAG_WCF
{


    public partial class PAG_Services : iPAG_Services
    {
        public List<DLB_LIB_BOLSON_CAB_DTO> qry_DLB_LIB_BOLSON_CAB_listado()
        {
            return new DLB_LIB_BOLSON_CAB_RDN().DLB_LIB_BOLSON_CAB_listado();
        }

        public List<DLB_LIB_BOLSON_CAB_DTO> qry_DLB_LIB_BOLSON_CAB_filtrado(DLB_LIB_BOLSON_CAB_DTO precDto)
        {
            return new DLB_LIB_BOLSON_CAB_RDN().DLB_LIB_BOLSON_CAB_filtrado(precDto);
        }

        public DLB_LIB_BOLSON_CAB_DTO ins_DLB_LIB_BOLSON_CAB_inserta(DLB_LIB_BOLSON_CAB_DTO precDto)
        {
            return new DLB_LIB_BOLSON_CAB_RDN().DLB_LIB_BOLSON_CAB_inserta(precDto);
        }

        public DLB_LIB_BOLSON_CAB_DTO upd_DLB_LIB_BOLSON_CAB_actualiza(DLB_LIB_BOLSON_CAB_DTO precDto)
        {
            return new DLB_LIB_BOLSON_CAB_RDN().DLB_LIB_BOLSON_CAB_actualiza(precDto);
        }

        public DLB_LIB_BOLSON_CAB_DTO del_DLB_LIB_BOLSON_CAB_elimina(DLB_LIB_BOLSON_CAB_DTO precDto)
        {
            return new DLB_LIB_BOLSON_CAB_RDN().DLB_LIB_BOLSON_CAB_elimina(precDto);
        }
        public DLB_LIB_BOLSON_CAB_DTO upd_DLB_LIB_BOLSON_CAB_verifica(DLB_LIB_BOLSON_CAB_DTO precDto)
        {
            return new DLB_LIB_BOLSON_CAB_RDN().DLB_LIB_BOLSON_CAB_verifica(precDto);
        }
        public DLB_LIB_BOLSON_CAB_DTO upd_DLB_LIB_BOLSON_CAB_desverifica(DLB_LIB_BOLSON_CAB_DTO precDto)
        {
            return new DLB_LIB_BOLSON_CAB_RDN().DLB_LIB_BOLSON_CAB_desverifica(precDto);
        }
        public DLB_LIB_BOLSON_CAB_DTO upd_DLB_LIB_BOLSON_CAB_aprueba(DLB_LIB_BOLSON_CAB_DTO precDto)
        {
            return new DLB_LIB_BOLSON_CAB_RDN().DLB_LIB_BOLSON_CAB_aprueba(precDto);
        }

    }
}
