//------------------------------------------------------------------------------
//                         Secretaria de Finanzas
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using PAG_DA;
using PAG_DTO;
using PAG_INTERFACES;
using PAG_MAPPERS;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Linq;
using System.ServiceModel;


namespace PAG_WCF
{
    
    
    public partial class PAG_Services : iPAG_Services
    {
        public List<DTP_DOCUMENTOS_DET_DTO> qry_DTP_DOCUMENTOS_DET_listado()
        {
            return new DTP_DOCUMENTOS_DET_RDN().DTP_DOCUMENTOS_DET_listado();
        }

        public List<DTP_DOCUMENTOS_DET_DTO> qry_DTP_DOCUMENTOS_DET_filtrado(DTP_DOCUMENTOS_DET_DTO precDto)
        {
            return new DTP_DOCUMENTOS_DET_RDN().DTP_DOCUMENTOS_DET_filtrado(precDto);
        }

        public DTP_DOCUMENTOS_DET_DTO ins_DTP_DOCUMENTOS_DET_inserta(DTP_DOCUMENTOS_DET_DTO precDto)
        {
            return new DTP_DOCUMENTOS_DET_RDN().DTP_DOCUMENTOS_DET_inserta(precDto);
        }

        public DTP_DOCUMENTOS_DET_DTO upd_DTP_DOCUMENTOS_DET_actualiza(DTP_DOCUMENTOS_DET_DTO precDto)
        {
            return new DTP_DOCUMENTOS_DET_RDN().DTP_DOCUMENTOS_DET_actualiza(precDto);
        }

        public DTP_DOCUMENTOS_DET_DTO del_DTP_DOCUMENTOS_DET_elimina(params object[] pkeysDto)
        {
            return new DTP_DOCUMENTOS_DET_RDN().DTP_DOCUMENTOS_DET_elimina(pkeysDto);
        }
        public void del_DTP_DOCUMENTOS_DET_borrar(DTP_DOCUMENTOS_DET_DTO precDto)
        {
            new DTP_DOCUMENTOS_DET_RDN().DTP_DOCUMENTOS_DET_borrar(precDto);
        }
    }
}
