//------------------------------------------------------------------------------
//                         Secretaria de Finanzas
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using PAG_DA;
using PAG_DTO;
using PAG_INTERFACES;
using PAG_MAPPERS;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Linq;
using System.ServiceModel;


namespace PAG_WCF
{
    
    
    public partial class PAG_Services : iPAG_Services
    {
        public List<TPR_TIPOS_PROGRAMACION_DTO> qry_TPR_TIPOS_PROGRAMACION_listado()
        {
            return new TPR_TIPOS_PROGRAMACION_RDN().TPR_TIPOS_PROGRAMACION_listado();
        }

        public List<TPR_TIPOS_PROGRAMACION_DTO> qry_TPR_TIPOS_PROGRAMACION_filtrado(TPR_TIPOS_PROGRAMACION_DTO precDto)
        {
            return new TPR_TIPOS_PROGRAMACION_RDN().TPR_TIPOS_PROGRAMACION_filtrado(precDto);
        }

        public TPR_TIPOS_PROGRAMACION_DTO ins_TPR_TIPOS_PROGRAMACION_inserta(TPR_TIPOS_PROGRAMACION_DTO precDto)
        {
            return new TPR_TIPOS_PROGRAMACION_RDN().TPR_TIPOS_PROGRAMACION_inserta(precDto);
        }

        public TPR_TIPOS_PROGRAMACION_DTO upd_TPR_TIPOS_PROGRAMACION_actualiza(TPR_TIPOS_PROGRAMACION_DTO precDto)
        {
            return new TPR_TIPOS_PROGRAMACION_RDN().TPR_TIPOS_PROGRAMACION_actualiza(precDto);
        }

        public TPR_TIPOS_PROGRAMACION_DTO del_TPR_TIPOS_PROGRAMACION_elimina(params object[] pkeysDto)
        {
            return new TPR_TIPOS_PROGRAMACION_RDN().TPR_TIPOS_PROGRAMACION_elimina(pkeysDto);
        }
        public List<TPR_TIPOS_PROGRAMACION_DTO> qry_TPR_TIPOS_PROGRAMACION_filtradoDocto(DTP_TIPOS_PROGRA_DET_DTO precTiposProgram)
        {
            return new TPR_TIPOS_PROGRAMACION_RDN().TPR_TIPOS_PROGRAMACION_filtradoDocto(precTiposProgram);
        }


    }
}
