//------------------------------------------------------------------------------
//                         Secretaria de Finanzas
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using PAG_DTO;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.ServiceModel;
using System.Text;
using System.Threading.Tasks;


namespace PAG_INTERFACES
{
    
    
    public partial interface iPAG_Services
    {
        
        [OperationContract]
        List<DLB_LIB_BOLSON_CAB_DTO> qry_DLB_LIB_BOLSON_CAB_listado();
        
        [OperationContract]
        List<DLB_LIB_BOLSON_CAB_DTO> qry_DLB_LIB_BOLSON_CAB_filtrado(DLB_LIB_BOLSON_CAB_DTO precDto);
        
        [OperationContract]
        DLB_LIB_BOLSON_CAB_DTO ins_DLB_LIB_BOLSON_CAB_inserta(DLB_LIB_BOLSON_CAB_DTO precDto);
        
        [OperationContract]
        DLB_LIB_BOLSON_CAB_DTO upd_DLB_LIB_BOLSON_CAB_actualiza(DLB_LIB_BOLSON_CAB_DTO precDto);

        [OperationContract]
        DLB_LIB_BOLSON_CAB_DTO del_DLB_LIB_BOLSON_CAB_elimina(DLB_LIB_BOLSON_CAB_DTO precDto);

        [OperationContract]
        DLB_LIB_BOLSON_CAB_DTO upd_DLB_LIB_BOLSON_CAB_verifica(DLB_LIB_BOLSON_CAB_DTO precDto);
        [OperationContract]
        DLB_LIB_BOLSON_CAB_DTO upd_DLB_LIB_BOLSON_CAB_desverifica(DLB_LIB_BOLSON_CAB_DTO precDto);
        [OperationContract]
        DLB_LIB_BOLSON_CAB_DTO upd_DLB_LIB_BOLSON_CAB_aprueba(DLB_LIB_BOLSON_CAB_DTO precDto);
    }
}
