//------------------------------------------------------------------------------
//                         Secretaria de Finanzas
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using PAG_DTO;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.ServiceModel;
using System.Text;
using System.Threading.Tasks;


namespace PAG_INTERFACES
{
    
    
    public partial interface iPAG_Services
    {
        
        [OperationContract]
        List<DTP_TIPOS_PROGRA_DET_DTO> qry_DTP_TIPOS_PROGRA_DET_listado();
        
        [OperationContract]
        List<DTP_TIPOS_PROGRA_DET_DTO> qry_DTP_TIPOS_PROGRA_DET_filtrado(DTP_TIPOS_PROGRA_DET_DTO precDto);
        
        [OperationContract]
        DTP_TIPOS_PROGRA_DET_DTO ins_DTP_TIPOS_PROGRA_DET_inserta(DTP_TIPOS_PROGRA_DET_DTO precDto);
        
        [OperationContract]
        DTP_TIPOS_PROGRA_DET_DTO upd_DTP_TIPOS_PROGRA_DET_actualiza(DTP_TIPOS_PROGRA_DET_DTO precDto);
        
        [OperationContract]
        DTP_TIPOS_PROGRA_DET_DTO del_DTP_TIPOS_PROGRA_DET_elimina(params object[] pkeysDto);

        [OperationContract]
        void del_DTP_TIPOS_PROGRA_DET_borrar(DTP_TIPOS_PROGRA_DET_DTO precDto);

        [OperationContract]
        List<DTP_TIPOS_PROGRA_DET_DTO> ins_DTP_TIPOS_PROGRA_DET_insertaArreglo(List<DTP_TIPOS_PROGRA_DET_DTO> precDto);

    }
}
