//------------------------------------------------------------------------------
//                         Secretaria de Finanzas
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using PAG_DTO;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.ServiceModel;
using System.Text;
using System.Threading.Tasks;


namespace PAG_INTERFACES
{
    
    
    public partial interface iPAG_Services
    {
        
        [OperationContract]
        List<DTP_TIPOS_PROGRA_CAB_DTO> qry_DTP_TIPOS_PROGRA_CAB_listado();
        
        [OperationContract]
        List<DTP_TIPOS_PROGRA_CAB_DTO> qry_DTP_TIPOS_PROGRA_CAB_filtrado(DTP_TIPOS_PROGRA_CAB_DTO precDto);
        
        [OperationContract]
        DTP_TIPOS_PROGRA_CAB_DTO ins_DTP_TIPOS_PROGRA_CAB_inserta(DTP_TIPOS_PROGRA_CAB_DTO precDto);
        
        [OperationContract]
        DTP_TIPOS_PROGRA_CAB_DTO upd_DTP_TIPOS_PROGRA_CAB_actualiza(DTP_TIPOS_PROGRA_CAB_DTO precDto);

        [OperationContract]
        DTP_TIPOS_PROGRA_CAB_DTO del_DTP_TIPOS_PROGRA_CAB_elimina(DTP_TIPOS_PROGRA_CAB_DTO precDto);

        [OperationContract]
        DTP_TIPOS_PROGRA_CAB_DTO upd_DTP_TIPOS_PROGRA_CAB_verifica(DTP_TIPOS_PROGRA_CAB_DTO precDto);

        [OperationContract]
        DTP_TIPOS_PROGRA_CAB_DTO upd_DTP_TIPOS_PROGRA_CAB_desverifica(DTP_TIPOS_PROGRA_CAB_DTO precDto);

        [OperationContract]
        DTP_TIPOS_PROGRA_CAB_DTO upd_DTP_TIPOS_PROGRA_CAB_aprueba(DTP_TIPOS_PROGRA_CAB_DTO precDto);
    }
}
