//------------------------------------------------------------------------------
//                         Secretaria de Finanzas
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using PAG_DTO;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.ServiceModel;
using System.Text;
using System.Threading.Tasks;


namespace PAG_INTERFACES
{
    
    
    public partial interface iPAG_Services
    {
        
        [OperationContract]
        List<TPR_DETALLES_DTO> qry_TPR_DETALLES_listado();
        
        [OperationContract]
        List<TPR_DETALLES_DTO> qry_TPR_DETALLES_filtrado(TPR_DETALLES_DTO precDto);
        
        [OperationContract]
        TPR_DETALLES_DTO ins_TPR_DETALLES_inserta(TPR_DETALLES_DTO precDto);
        
        [OperationContract]
        TPR_DETALLES_DTO upd_TPR_DETALLES_actualiza(TPR_DETALLES_DTO precDto);
        
        [OperationContract]
        TPR_DETALLES_DTO del_TPR_DETALLES_elimina(params object[] pkeysDto);
    }
}
