//------------------------------------------------------------------------------
//                         Secretaria de Finanzas
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using PAG_DA;
using PAG_DTO;
using PAG_INTERFACES;
using PAG_MAPPERS;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Linq;
using System.ServiceModel;


namespace PAG_WCF
{
    
    
    public class DCO_DOCUMENTOS_COLUMNAS_FILTER : ExpressionBuilder<DCO_DOCUMENTOS_COLUMNAS>
    {
        
        public override void build(DCO_DOCUMENTOS_COLUMNAS da)
        {
            if (String.IsNullOrEmpty(da.ID_DOCUMENTO) == false) and(col => col.ID_DOCUMENTO == da.ID_DOCUMENTO);
            if (da.ID_COLUMNA > 0) and(col => col.ID_COLUMNA == da.ID_COLUMNA);
            if (String.IsNullOrEmpty(da.ESPECIAL) == false) and(col => col.ESPECIAL == da.ESPECIAL);
            if (String.IsNullOrEmpty(da.API_ESTADO) == false) and(col => col.API_ESTADO.Contains(da.API_ESTADO));
        }
    }
}
