//------------------------------------------------------------------------------
//                         Secretaria de Finanzas
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using PAG_DA;
using PAG_DTO;
using PAG_INTERFACES;
using PAG_MAPPERS;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Linq;
using System.ServiceModel;


namespace PAG_WCF
{
    
    
    public class DLB_LIB_BOLSON_CAB_FILTER : ExpressionBuilder<DLB_LIB_BOLSON_CAB>
    {
        
        public override void build(DLB_LIB_BOLSON_CAB da)
        {
            if (da.GESTION > 0) and(col => col.GESTION == da.GESTION);
            if (da.INSTITUCION > 0) and(col => col.INSTITUCION == da.INSTITUCION);
            if (da.GA > 0) and(col => col.GA == da.GA);
            if (da.NRO_DOCUMENTO > 0) and(col => col.NRO_DOCUMENTO == da.NRO_DOCUMENTO);
            if (da.DPTO_LUGAR > 0) and(col => col.DPTO_LUGAR == da.DPTO_LUGAR);
            if (da.MUN_LUGAR > 0) and(col => col.MUN_LUGAR == da.MUN_LUGAR);
            if (String.IsNullOrEmpty(da.TIPO_OPERACION) == false) and(col => col.TIPO_OPERACION.Contains(da.TIPO_OPERACION));
            if (String.IsNullOrEmpty(da.API_ESTADO) == false) and(col => col.API_ESTADO.Contains(da.API_ESTADO));
            and(col => col.API_ESTADO != "ELIMINADO");
        }
    }
}
