//------------------------------------------------------------------------------
//                         Secretaria de Finanzas
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using PAG_DA;
using PAG_DTO;
using PAG_INTERFACES;
using PAG_MAPPERS;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Linq;
using System.ServiceModel;


namespace PAG_WCF
{
    
    
    public class DTP_DETALLES_DET_FILTER : ExpressionBuilder<DTP_DETALLES_DET>
    {
        
        public override void build(DTP_DETALLES_DET da)
        {
            and(col => col.GESTION == da.GESTION);
            and(col => col.INSTITUCION == da.INSTITUCION);
            and(col => col.GA == da.GA);
            and(col => col.NRO_DOCUMENTO == da.NRO_DOCUMENTO);
            and(col => col.INSTITUCION_PROG == da.INSTITUCION_PROG);
            and(col => col.GA_PROG == da.GA_PROG);
            and(col => col.TIPO_PROGRAMACION == da.TIPO_PROGRAMACION);
            and(col => col.SECUENCIA_DOC == da.SECUENCIA_DOC);
            if (da.SECUENCIA_DET > 0) and(col => col.SECUENCIA_DET == da.SECUENCIA_DET);
            if (String.IsNullOrEmpty(da.ID_DOCUMENTO) == false) and(col => col.ID_DOCUMENTO.Contains(da.ID_DOCUMENTO));
            if (da.ID_COLUMNA > 0) and(col => col.ID_COLUMNA == da.ID_COLUMNA);
            if (da.VALOR_NUMERO > 0) and(col => col.VALOR_NUMERO == da.VALOR_NUMERO);
            if (String.IsNullOrEmpty(da.VALOR_CADENA) == false) and(col => col.VALOR_CADENA.Contains(da.VALOR_CADENA));
            if (String.IsNullOrEmpty(da.API_ESTADO) == false) and(col => col.API_ESTADO.Contains(da.API_ESTADO));
        }
    }
}