//------------------------------------------------------------------------------
//                         Secretaria de Finanzas
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using PAG_DA;
using PAG_DTO;
using PAG_INTERFACES;
using PAG_MAPPERS;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Linq;
using System.ServiceModel;


namespace PAG_WCF
{
    
    
    public class PRG_LIBRETAS_BOLSON_FILTER : ExpressionBuilder<PRG_LIBRETAS_BOLSON>
    {
        
        public override void build(PRG_LIBRETAS_BOLSON da)
        {
            if (da.GESTION > 0) and(col => col.GESTION == da.GESTION);
            if (da.INSTITUCION > 0) and(col => col.INSTITUCION == da.INSTITUCION);
            if (da.GA > 0) and(col => col.GA == da.GA);
            if (da.BANCO > 0) and(col => col.BANCO == da.BANCO);
            if (String.IsNullOrEmpty(da.CUENTA) == false) and(col => col.CUENTA.Contains(da.CUENTA));
            if (String.IsNullOrEmpty(da.LIBRETA) == false) and(col => col.LIBRETA.Contains(da.LIBRETA));
            if (String.IsNullOrEmpty(da.MONEDA) == false) and(col => col.MONEDA.Contains(da.MONEDA));
            if (da.FUENTE > 0) and(col => col.FUENTE == da.FUENTE);
            if (String.IsNullOrEmpty(da.API_ESTADO) == false) and(col => col.API_ESTADO.Contains(da.API_ESTADO));
        }
    }
}
