//------------------------------------------------------------------------------
//                         Secretaria de Finanzas
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using PAG_DA;
using PAG_DTO;
using PAG_INTERFACES;
using PAG_MAPPERS;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Linq;
using System.ServiceModel;


namespace PAG_WCF
{
    
    
    public class TPR_TIPOS_PROGRAMACION_FILTER : ExpressionBuilder<TPR_TIPOS_PROGRAMACION>
    {
        
        public override void build(TPR_TIPOS_PROGRAMACION da)
        {
            if (da.INSTITUCION > 0) and(col => col.INSTITUCION == da.INSTITUCION);
            if (da.TIPO_PROGRAMACION > 0) and(col => col.TIPO_PROGRAMACION == da.TIPO_PROGRAMACION);
            if (String.IsNullOrEmpty(da.DESC_TIPO_PROGRAMACION) == false) and(col => col.DESC_TIPO_PROGRAMACION.Contains(da.DESC_TIPO_PROGRAMACION));
            if (String.IsNullOrEmpty(da.ESPECIAL) == false) and(col => col.ESPECIAL.Contains(da.ESPECIAL));
            if (String.IsNullOrEmpty(da.API_ESTADO) == false) and(col => col.API_ESTADO.Contains(da.API_ESTADO));
            and(col => col.API_ESTADO != "ELIMINADO");
        }
    }
}
