//------------------------------------------------------------------------------
//                         Secretaria de Finanzas
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using PAG_DA;
using PAG_DTO;
using PAG_INTERFACES;
using PAG_MAPPERS;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Linq;
using System.ServiceModel;


namespace PAG_WCF
{
    
    
    public class TPR_DOCUMENTOS_FILTER : ExpressionBuilder<TPR_DOCUMENTOS>
    {
        
        public override void build(TPR_DOCUMENTOS da)
        {
            if (da.INSTITUCION > 0) and(col => col.INSTITUCION == da.INSTITUCION);
            if (da.TIPO_PROGRAMACION > 0) and(col => col.TIPO_PROGRAMACION == da.TIPO_PROGRAMACION);
            if (da.SECUENCIA_DOC > 0) and(col => col.SECUENCIA_DOC == da.SECUENCIA_DOC);
            if (String.IsNullOrEmpty(da.ID_DOCUMENTO) == false) and(col => col.ID_DOCUMENTO.Contains(da.ID_DOCUMENTO));
            if (String.IsNullOrEmpty(da.OBSERVACION) == false) and(col => col.OBSERVACION.Contains(da.OBSERVACION));
            if (String.IsNullOrEmpty(da.API_ESTADO) == false) and(col => col.API_ESTADO.Contains(da.API_ESTADO));
        }
    }
}
