//------------------------------------------------------------------------------
//                         Secretaria de Finanzas
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using PAG_DA;
using PAG_DTO;
using PAG_INTERFACES;
using PAG_MAPPERS;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Linq;
using System.ServiceModel;


namespace PAG_WCF
{
    
    
    public class DCO_DOCUMENTOS_COLUMNAS_RDN
    {

        public List<DCO_DOCUMENTOS_COLUMNAS_DTO> DCO_DOCUMENTOS_COLUMNAS_listado()
        {
            // TODO: Desarrolle su Codigo Aqui.
            List<DCO_DOCUMENTOS_COLUMNAS_DTO> ltDCO_DOCUMENTOS_COLUMNAS = new List<DCO_DOCUMENTOS_COLUMNAS_DTO>();
            //try
            //{
                using (PAG_Entities context = new PAG_Entities(PAG_Security.DictionaryClaims))
                {
                    IQueryable<DCO_DOCUMENTOS_COLUMNAS> query;
                    query = from rec in context.DCO_DOCUMENTOS_COLUMNAS
                            select rec;
                    foreach (var item in query)
                    {
                        var prec = item.ToDto();
                        obtenerValoresColumna(ref prec);
                        ltDCO_DOCUMENTOS_COLUMNAS.Add(prec);
                    }
                }
            //}
            //catch (Exception Ex)
            //{
            //    throw new FaultException(PAG_ServicesUtil.ErrorPAGDescDefecto, new FaultCode(PAG_ServicesUtil.ErrorPAGCodDefecto), Ex.InnerException.InnerException.Message);
            //}
            return ltDCO_DOCUMENTOS_COLUMNAS;
        }

        public List<DCO_DOCUMENTOS_COLUMNAS_DTO> DCO_DOCUMENTOS_COLUMNAS_filtrado(DCO_DOCUMENTOS_COLUMNAS_DTO precDto)
        {
            // TODO: Desarrolle su Codigo Aqui.
            List<DCO_DOCUMENTOS_COLUMNAS_DTO> ltDCO_DOCUMENTOS_COLUMNAS = new List<DCO_DOCUMENTOS_COLUMNAS_DTO>();
            //try
            //{
                using (PAG_Entities context = new PAG_Entities(PAG_Security.DictionaryClaims))
                {
                    var entity = precDto.ToEntity();
                    var filters = new DCO_DOCUMENTOS_COLUMNAS_FILTER();
                    var delegates = filters.GetExpression(entity);
                    //Aplicar pFilters Dinamico
                    if (!filters.hasFilters) { return ltDCO_DOCUMENTOS_COLUMNAS; };
                    var filteredCollection = context.DCO_DOCUMENTOS_COLUMNAS.Where(delegates).ToList();
                    //Transformar pFilter Dinamico
                    foreach (var item in filteredCollection) {
                        var prec = item.ToDto();
                        obtenerValoresColumna(ref prec);
                        ltDCO_DOCUMENTOS_COLUMNAS.Add(prec);
                    }
                }
            //}
            //catch (Exception Ex)
            //{
            //    throw new FaultException(PAG_ServicesUtil.ErrorPAGDescDefecto, new FaultCode(PAG_ServicesUtil.ErrorPAGCodDefecto), Ex.InnerException.InnerException.Message);
            //}
            return ltDCO_DOCUMENTOS_COLUMNAS;
        }

        public DCO_DOCUMENTOS_COLUMNAS_DTO DCO_DOCUMENTOS_COLUMNAS_inserta(DCO_DOCUMENTOS_COLUMNAS_DTO precDto)
        {
            // TODO: Desarrolle su Codigo Aqui.
            //return new DCO_DOCUMENTOS_COLUMNAS_DTO();
            throw new FaultException("PAG-00001 Administrado por el àrea de desarrollo", new FaultCode("PAG-00001"));
        }

        public DCO_DOCUMENTOS_COLUMNAS_DTO DCO_DOCUMENTOS_COLUMNAS_actualiza(DCO_DOCUMENTOS_COLUMNAS_DTO precDto)
        {
            // TODO: Desarrolle su Codigo Aqui.
            //return new DCO_DOCUMENTOS_COLUMNAS_DTO();
            throw new FaultException("PAG-00001 Administrado por el àrea de desarrollo", new FaultCode("PAG-00001"));
        }

        public DCO_DOCUMENTOS_COLUMNAS_DTO DCO_DOCUMENTOS_COLUMNAS_elimina(params object[] pkeysDto)
        {
            // TODO: Desarrolle su Codigo Aqui.
            //return new DCO_DOCUMENTOS_COLUMNAS_DTO();
            throw new FaultException("PAG-00001 Administrado por el àrea de desarrollo", new FaultCode("PAG-00001"));
        }
        public void obtenerValoresColumna(ref DCO_DOCUMENTOS_COLUMNAS_DTO precDto)
        {
            using (PAG_Entities context = new PAG_Entities(PAG_Security.DictionaryClaims))
            {
                var prec = precDto;
                // Valores de columna
                List<DCO_COLUMNAS> lov_col = context.DCO_COLUMNAS.Where(col => col.ID_COLUMNA == prec.ID_COLUMNA).ToList();
                if (lov_col.Count > 0) {
                    precDto.DESC_COLUMNA = lov_col.FirstOrDefault().DESC_COLUMNA;
                    precDto.TIPO_COLUMNA = lov_col.FirstOrDefault().TIPO_COLUMNA;
                }
                // Descripción de Docuemnto
                List<DCO_DOCUMENTOS> lov_doc = context.DCO_DOCUMENTOS.Where(col => col.ID_DOCUMENTO == prec.ID_DOCUMENTO).ToList();
                if (lov_doc.Count > 0)
                {
                    precDto.DESC_DOCUMENTO = lov_doc.FirstOrDefault().DESC_DOCUMENTO;
                }
            }
        }
    }
}
