//------------------------------------------------------------------------------
//                         Secretaria de Finanzas
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using PAG_DA;
using PAG_DTO;
using PAG_INTERFACES;
using PAG_MAPPERS;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.ServiceModel;
//
using System.Runtime.Serialization;
using System.Reflection;
using System.Diagnostics;
using System.ServiceModel.Channels;


namespace PAG_WCF
{
    
    
    public class DCO_COLUMNAS_RDN
    {
        
        public List<DCO_COLUMNAS_DTO> DCO_COLUMNAS_listado()
        {
            // TODO: Desarrolle su Codigo Aqui.
            List<DCO_COLUMNAS_DTO> ltDCO_COLUMNAS = new List<DCO_COLUMNAS_DTO>();
            //try
            //{
                using (PAG_Entities context = new PAG_Entities(PAG_Security.DictionaryClaims))
                {
                    IQueryable<DCO_COLUMNAS> query;
                    query = from rec in context.DCO_COLUMNAS
                            orderby rec.DESC_COLUMNA
                            select rec;
                    foreach (var item in query)
                    {
                        ltDCO_COLUMNAS.Add(item.ToDto());
                    }
                }
            //}
            //catch (Exception Ex)
            //{
            //    throw new FaultException(PAG_ServicesUtil.ErrorPAGDescDefecto, new FaultCode(PAG_ServicesUtil.ErrorPAGCodDefecto), Ex.InnerException.InnerException.Message);
            //}
            return ltDCO_COLUMNAS;
        }

        public List<DCO_COLUMNAS_DTO> DCO_COLUMNAS_filtrado(DCO_COLUMNAS_DTO precDto)
        {
            // TODO: Desarrolle su Codigo Aqui.
            List<DCO_COLUMNAS_DTO> ltDCO_COLUMNAS = new List<DCO_COLUMNAS_DTO>();
            //try
            //{
                using (PAG_Entities context = new PAG_Entities(PAG_Security.DictionaryClaims))
                {
                    var entity = precDto.ToEntity();
                    var filters = new DCO_COLUMNAS_FILTER();
                    var delegates = filters.GetExpression(entity);
                    //Aplicar pFilters Dinamico
                    if (!filters.hasFilters) { return ltDCO_COLUMNAS; };
                    var filteredCollection = context.DCO_COLUMNAS.OrderBy(x => x.DESC_COLUMNA).Where(delegates).ToList();
                    //Transformar pFilter Dinamico
                    foreach (var item in filteredCollection) { ltDCO_COLUMNAS.Add(item.ToDto()); }
                }
            //}
            //catch (Exception Ex)
            //{
            //    throw new FaultException(PAG_ServicesUtil.ErrorPAGDescDefecto, new FaultCode(PAG_ServicesUtil.ErrorPAGCodDefecto), Ex.InnerException.InnerException.Message);
            //}
            return ltDCO_COLUMNAS;
        }

        public DCO_COLUMNAS_DTO DCO_COLUMNAS_inserta(DCO_COLUMNAS_DTO precDto)
        {
            // TODO: Desarrolle su Codigo Aqui.
            //return new DCO_COLUMNAS_DTO();
            throw new FaultException("PAG-00001 Administrado por el àrea de desarrollo", new FaultCode("PAG-00001"));
        }

        public DCO_COLUMNAS_DTO DCO_COLUMNAS_actualiza(DCO_COLUMNAS_DTO precDto)
        {
            // TODO: Desarrolle su Codigo Aqui.
            //return new DCO_COLUMNAS_DTO();
            throw new FaultException("PAG-00001 Administrado por el àrea de desarrollo", new FaultCode("PAG-00001"));
        }

        public DCO_COLUMNAS_DTO DCO_COLUMNAS_elimina(params object[] pkeysDto)
        {
            // TODO: Desarrolle su Codigo Aqui.
            //return new DCO_COLUMNAS_DTO();
            throw new FaultException("PAG-00001 Administrado por el àrea de desarrollo", new FaultCode("PAG-00001"));
        }
    }
}
