//------------------------------------------------------------------------------
//                         Secretaria de Finanzas
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using PAG_DA;
using PAG_DTO;
using PAG_INTERFACES;
using PAG_MAPPERS;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.ServiceModel;

namespace PAG_WCF
{
    
    
    public class DCO_DOCUMENTOS_RDN
    {

        public List<DCO_DOCUMENTOS_DTO> DCO_DOCUMENTOS_listado()
        {
            // TODO: Desarrolle su Codigo Aqui.
            List<DCO_DOCUMENTOS_DTO> ltDCO_DOCUMENTOS = new List<DCO_DOCUMENTOS_DTO>();
            //try
            //{
                using (PAG_Entities context = new PAG_Entities(PAG_Security.DictionaryClaims))
                {
                    IQueryable<DCO_DOCUMENTOS> query;
                    query = from rec in context.DCO_DOCUMENTOS
                            select rec;
                    foreach (var item in query)
                    {
                        ltDCO_DOCUMENTOS.Add(item.ToDto());
                    }
                }
            //}
            //catch (Exception Ex)
            //{
            //    throw new FaultException(PAG_ServicesUtil.ErrorPAGDescDefecto, new FaultCode(PAG_ServicesUtil.ErrorPAGCodDefecto), Ex.InnerException.InnerException.Message);
            //}
            return ltDCO_DOCUMENTOS;
        }

        public List<DCO_DOCUMENTOS_DTO> DCO_DOCUMENTOS_filtrado(DCO_DOCUMENTOS_DTO precDto)
        {
            // TODO: Desarrolle su Codigo Aqui.
            List<DCO_DOCUMENTOS_DTO> ltDCO_DOCUMENTOS = new List<DCO_DOCUMENTOS_DTO>();
            //try
            //{
                using (PAG_Entities context = new PAG_Entities(PAG_Security.DictionaryClaims))
                {
                    var entity = precDto.ToEntity();
                    var filters = new DCO_DOCUMENTOS_FILTER();
                    var delegates = filters.GetExpression(entity);
                    //Aplicar pFilters Dinamico
                    if (!filters.hasFilters) { return ltDCO_DOCUMENTOS; };
                    var filteredCollection = context.DCO_DOCUMENTOS.Where(delegates).ToList();
                    //Transformar pFilter Dinamico
                    foreach (var item in filteredCollection) { ltDCO_DOCUMENTOS.Add(item.ToDto()); }
                }
            //}
            //catch (Exception Ex)
            //{
            //    throw new FaultException(PAG_ServicesUtil.ErrorPAGDescDefecto, new FaultCode(PAG_ServicesUtil.ErrorPAGCodDefecto), Ex.InnerException.InnerException.Message);
            //}
            return ltDCO_DOCUMENTOS;
        }

        public DCO_DOCUMENTOS_DTO DCO_DOCUMENTOS_inserta(DCO_DOCUMENTOS_DTO precDto)
        {
            // TODO: Desarrolle su Codigo Aqui.
            //return new DCO_DOCUMENTOS_DTO();
            throw new FaultException("PAG-00001 Administrado por el àrea de desarrollo", new FaultCode("PAG-00001"));
        }

        public DCO_DOCUMENTOS_DTO DCO_DOCUMENTOS_actualiza(DCO_DOCUMENTOS_DTO precDto)
        {
            // TODO: Desarrolle su Codigo Aqui.
            //return new DCO_DOCUMENTOS_DTO();
            throw new FaultException("PAG-00001 Administrado por el àrea de desarrollo", new FaultCode("PAG-00001"));
        }

        public DCO_DOCUMENTOS_DTO DCO_DOCUMENTOS_elimina(params object[] pkeysDto)
        {
            // TODO: Desarrolle su Codigo Aqui.
            //return new DCO_DOCUMENTOS_DTO();
            throw new FaultException("PAG-00001 Administrado por el àrea de desarrollo", new FaultCode("PAG-00001"));
        }
    }
}
