//------------------------------------------------------------------------------
//                         Secretaria de Finanzas
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using PAG_DA;
using PAG_DTO;
using PAG_INTERFACES;
using PAG_MAPPERS;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Linq;
using System.ServiceModel;
using System.Transactions;

namespace PAG_WCF
{
    
    
    public class DLB_LIB_BOLSON_DET_RDN
    {
        // Listado.
        public List<DLB_LIB_BOLSON_DET_DTO> DLB_LIB_BOLSON_DET_listado()
        {
            // TODO: Desarrolle su Codigo Aqui.
            List<DLB_LIB_BOLSON_DET_DTO> ltDLB_LIB_BOLSON_DET = new List<DLB_LIB_BOLSON_DET_DTO>();
            //try
            //{
                using (PAG_Entities context = new PAG_Entities(PAG_Security.DictionaryClaims))
                {
                    IQueryable<DLB_LIB_BOLSON_DET> query;
                    query = from rec in context.DLB_LIB_BOLSON_DET
                            select rec;
                    foreach (var item in query)
                    {
                        ltDLB_LIB_BOLSON_DET.Add(item.ToDto());
                    }
                }
            //}
            //catch (Exception Ex)
            //{
            //    throw new FaultException(PAG_ServicesUtil.ErrorPAGDescDefecto, new FaultCode(PAG_ServicesUtil.ErrorPAGCodDefecto), Ex.InnerException.InnerException.Message);
            //}
            return ltDLB_LIB_BOLSON_DET;
        }

        // Filtrado.
        public List<DLB_LIB_BOLSON_DET_DTO> DLB_LIB_BOLSON_DET_filtrado(DLB_LIB_BOLSON_DET_DTO precDto)
        {
            // TODO: Desarrolle su Codigo Aqui.
            List<DLB_LIB_BOLSON_DET_DTO> ltDLB_LIB_BOLSON_DET = new List<DLB_LIB_BOLSON_DET_DTO>();
            //try
            //{
                using (PAG_Entities context = new PAG_Entities(PAG_Security.DictionaryClaims))
                {
                    var entity = precDto.ToEntity();
                    var filters = new DLB_LIB_BOLSON_DET_FILTER();
                    var delegates = filters.GetExpression(entity);
                    //Aplicar pFilters Dinamico
                    if (!filters.hasFilters) { return ltDLB_LIB_BOLSON_DET; };
                    var filteredCollection = context.DLB_LIB_BOLSON_DET.Where(delegates).ToList();
                    //Transformar pFilter Dinamico
                    foreach (var item in filteredCollection) { ltDLB_LIB_BOLSON_DET.Add(item.ToDto()); }
                }
            //}
            //catch (Exception Ex)
            //{
            //    throw new FaultException(PAG_ServicesUtil.ErrorPAGDescDefecto, new FaultCode(PAG_ServicesUtil.ErrorPAGCodDefecto), Ex.InnerException.InnerException.Message);
            //}
            return ltDLB_LIB_BOLSON_DET;
        }

        // Inserta.
        public DLB_LIB_BOLSON_DET_DTO DLB_LIB_BOLSON_DET_inserta(DLB_LIB_BOLSON_DET_DTO precDto)
        {
            // TODO: Desarrolle su Codigo Aqui.
            using (PAG_Entities context = new PAG_Entities(PAG_Security.DictionaryClaims))
            {
                precDto.API_ESTADO = "INICIAL";
                precDto.API_TRANSACCION = "CREAR";
                precDto.USU_CRE = PAG_ServicesUtil.usuarioPAG;
                //Insert NewRow Client
                DLB_LIB_BOLSON_DET entity = new DLB_LIB_BOLSON_DET();
                //try
                //{
                    //Begin SavePoint
                    using (TransactionScope SavePoint = new TransactionScope())
                    {
                        entity = precDto.ToEntity();
                        context.DLB_LIB_BOLSON_DET.Add(entity);
                        context.SaveChanges();
                        SavePoint.Complete(); //Commit SavePoint
                    }//End SavePoint
                     //Retuning NewRow DataBase
                    precDto.GESTION = entity.GESTION;
                    precDto.INSTITUCION = entity.INSTITUCION;
                    precDto.GA = entity.GA;
                    precDto.NRO_DOCUMENTO = entity.NRO_DOCUMENTO;
                    precDto.SECUENCIA = entity.SECUENCIA;
                    precDto.PAG_INSTITUCION = entity.PAG_INSTITUCION;
                    precDto.PAG_GA = entity.PAG_GA;
                    precDto.LIB_GESTION = entity.LIB_GESTION;
                    precDto.LIB_BANCO = entity.LIB_BANCO;
                    precDto.LIB_CUENTA = entity.LIB_CUENTA;
                    precDto.LIB_LIBRETA = entity.LIB_LIBRETA;
                    precDto.FUENTE = entity.FUENTE;
                    //Retuning NewAudit DataBase
                    precDto.API_ESTADO = entity.API_ESTADO;
                    precDto.API_TRANSACCION = entity.API_TRANSACCION;
                    precDto.USU_CRE = entity.USU_CRE;
                    precDto.FEC_CRE = entity.FEC_CRE;
                    precDto.USU_MOD = null;
                    precDto.FEC_MOD = null;
                //}
                //catch (Exception ex)
                //{
                //    if (PAG_ServicesUtil.EsErrorORA(ex))
                //    { throw new FaultException(PAG_ServicesUtil.ObtDescExcepcion(ex, soloMensaje: true), new FaultCode(PAG_ServicesUtil.ObtCodExcepcion(ex))); };
                //    throw new FaultException(PAG_ServicesUtil.ErrorPAGDescDefecto, new FaultCode(PAG_ServicesUtil.ErrorPAGCodDefecto), ex.InnerException.Message);
                //}
            }
            //
            return precDto;
        }

        public List<DLB_LIB_BOLSON_DET_DTO> DLB_LIB_BOLSON_DET_insertaArreglo(List<DLB_LIB_BOLSON_DET_DTO> precDto)
        {
            // TODO: Desarrolle su Codigo Aqui.
            using (PAG_Entities context = new PAG_Entities(PAG_Security.DictionaryClaims))
            {
                
                 //try
                 //   {
                        //Begin SavePoint
                        using (TransactionScope SavePoint = new TransactionScope())
                        {
                            foreach (var item in precDto)
                            {

                                item.API_ESTADO = "INICIAL";
                                item.API_TRANSACCION = "CREAR";
                                item.USU_CRE = PAG_ServicesUtil.usuarioPAG;
                                //Insert NewRow Client
                                DLB_LIB_BOLSON_DET entity = new DLB_LIB_BOLSON_DET();
                                entity = item.ToEntity();
                                context.DLB_LIB_BOLSON_DET.Add(entity);
                                context.SaveChanges();
                                item.GESTION = entity.GESTION;
                                item.INSTITUCION = entity.INSTITUCION;
                                item.GA = entity.GA;
                                item.NRO_DOCUMENTO = entity.NRO_DOCUMENTO;
                                item.SECUENCIA = entity.SECUENCIA;
                                item.PAG_INSTITUCION = entity.PAG_INSTITUCION;
                                item.PAG_GA = entity.PAG_GA;
                                item.LIB_GESTION = entity.LIB_GESTION;
                                item.LIB_BANCO = entity.LIB_BANCO;
                                item.LIB_CUENTA = entity.LIB_CUENTA;
                                item.LIB_LIBRETA = entity.LIB_LIBRETA;
                                item.FUENTE = entity.FUENTE;
                                //Retuning NewAudit DataBase
                                item.API_ESTADO = entity.API_ESTADO;
                                item.API_TRANSACCION = entity.API_TRANSACCION;
                                item.USU_CRE = entity.USU_CRE;
                                item.FEC_CRE = entity.FEC_CRE;
                                item.USU_MOD = null;
                                item.FEC_MOD = null;
                            }
                            SavePoint.Complete(); //Commit SavePoint
                        }//End SavePoint
                        
                    //}
                    //catch (Exception ex)
                    //{
                    //    if (PAG_ServicesUtil.EsErrorORA(ex))
                    //    { throw new FaultException(PAG_ServicesUtil.ObtDescExcepcion(ex, soloMensaje: true), new FaultCode(PAG_ServicesUtil.ObtCodExcepcion(ex))); };
                    //    throw new FaultException(PAG_ServicesUtil.ErrorPAGDescDefecto, new FaultCode(PAG_ServicesUtil.ErrorPAGCodDefecto), ex.InnerException.Message);
                    //}
            }
            //
            return precDto;
        }

        // Actualiza
        public DLB_LIB_BOLSON_DET_DTO DLB_LIB_BOLSON_DET_actualiza(DLB_LIB_BOLSON_DET_DTO precDto)
        {
            // TODO: Desarrolle su Codigo Aqui.
            using (PAG_Entities context = new PAG_Entities(PAG_Security.DictionaryClaims))
            {
                //Validate RDN
                var entity = context.DLB_LIB_BOLSON_DET.Find(precDto.GESTION, precDto.INSTITUCION, precDto.GA, precDto.NRO_DOCUMENTO, precDto.SECUENCIA);
                if (entity == null) { throw new FaultException(PAG_ServicesUtil.ObtDescWFCExcepcion("PAG", 2, soloMensaje: true), new FaultCode(PAG_ServicesUtil.ObtCodWFCExcepcion("PAG", 2))); } /*"Registro NO Encontrado."*/
                List<API_TRANSICIONES> transicion = context.API_TRANSICIONES.Where(col => col.TABLA == "DLB_LIB_BOLSON_DET" && col.ESTADO_INICIAL == entity.API_ESTADO && col.TRANSACCION == precDto.API_TRANSACCION).ToList();
                if (transicion.Count == 0) { throw new FaultException(PAG_ServicesUtil.ObtDescWFCExcepcion("PAG", 4, soloMensaje: true), new FaultCode(PAG_ServicesUtil.ObtCodWFCExcepcion("PAG", 4))); } /*"Transición NO Definida en Flujo del Registro."*/
                //Assign Data NewRow
                var pEntity = precDto.ToEntity();
                entity.PAG_INSTITUCION = pEntity.PAG_INSTITUCION;
                entity.PAG_GA = pEntity.PAG_GA;
                entity.LIB_GESTION = pEntity.LIB_GESTION;
                entity.LIB_BANCO = pEntity.LIB_BANCO;
                entity.LIB_CUENTA = pEntity.LIB_CUENTA;
                entity.LIB_LIBRETA = pEntity.LIB_LIBRETA;
                entity.FUENTE = pEntity.FUENTE;
                entity.API_TRANSACCION = pEntity.API_TRANSACCION;
                entity.USU_MOD = PAG_ServicesUtil.usuarioPAG;
                //Update NewRow Cliente
                //try
                //{
                    //Begin SavePoint
                    using (TransactionScope SavePoint = new TransactionScope())
                    {
                        context.DLB_LIB_BOLSON_DET.Attach(entity);
                        var entry = context.Entry(entity);
                        entry.State = EntityState.Modified;
                        context.SaveChanges();
                        context.Entry(entity).Reload();
                        SavePoint.Complete(); //Commit SavePoint
                    }//End SavePoint
                     //Retuning NewAudit DataBase
                    precDto.API_ESTADO = entity.API_ESTADO;
                    precDto.API_TRANSACCION = entity.API_TRANSACCION;
                    precDto.USU_MOD = entity.USU_MOD;
                    precDto.FEC_MOD = entity.FEC_MOD;
                //}
                //catch (Exception ex)
                //{
                //    if (PAG_ServicesUtil.EsErrorORA(ex))
                //    { throw new FaultException(PAG_ServicesUtil.ObtDescExcepcion(ex, soloMensaje: true), new FaultCode(PAG_ServicesUtil.ObtCodExcepcion(ex))); };
                //    throw new FaultException(PAG_ServicesUtil.ErrorPAGDescDefecto, new FaultCode(PAG_ServicesUtil.ErrorPAGCodDefecto), ex.InnerException.Message);
                //}
            }
            return precDto;
        }

        // Elimina.
        public DLB_LIB_BOLSON_DET_DTO DLB_LIB_BOLSON_DET_elimina(params object[] pkeysDto)
        {
            // TODO: Desarrolle su Codigo Aqui.
            throw new FaultException("PAG-00001 Implementada en Base de Datos.", new FaultCode("PAG-00001"));
        }
        public void DLB_LIB_BOLSON_DET_borrar(DLB_LIB_BOLSON_DET_DTO precDto)
        {
            using (PAG_Entities context = new PAG_Entities(PAG_Security.DictionaryClaims))
            {
                var entity = new DLB_LIB_BOLSON_DET();
                //try
                //{
                    //Begin SavePoint
                    using (TransactionScope SavePoint = new TransactionScope())
                    {
                        entity = context.DLB_LIB_BOLSON_DET.Find(precDto.GESTION, precDto.INSTITUCION, precDto.GA, precDto.NRO_DOCUMENTO, precDto.SECUENCIA);
                        context.DLB_LIB_BOLSON_DET.Remove(entity);
                        context.SaveChanges();
                        SavePoint.Complete(); //Commit SavePoint
                    }//End SavePoint
                //}
                //catch (Exception ex)
                //{
                //    if (PAG_ServicesUtil.EsErrorORA(ex))
                //    { throw new FaultException(PAG_ServicesUtil.ObtDescExcepcion(ex, soloMensaje: true), new FaultCode(PAG_ServicesUtil.ObtCodExcepcion(ex))); };
                //    throw new FaultException(PAG_ServicesUtil.ErrorPAGDescDefecto, new FaultCode(PAG_ServicesUtil.ErrorPAGCodDefecto), ex.InnerException.Message);
                //}
            }
        }

        // DESCRIPCIONES.
        private void obtenerDescripciones(ref DLB_LIB_BOLSON_DET_DTO precDto)
        {
            using (PAG_Entities context = new PAG_Entities(PAG_Security.DictionaryClaims))
            {
                var prec = precDto;
                // Descripción de institución
                List<INSTITUCIONES> lov_ins = context.INSTITUCIONES.Where(col => col.INSTITUCION == prec.PAG_INSTITUCION).ToList();
                if (lov_ins.Count > 0) { precDto.DESC_INSTITUCION = lov_ins.FirstOrDefault().DESC_INSTITUCION; }
                // Descripción de GA
                var entityGA = new GERENCIAS_ADMINISTRATIVAS();
                entityGA.GESTION = prec.GESTION;
                entityGA.INSTITUCION = prec.PAG_INSTITUCION;
                entityGA.GA = prec.PAG_GA;
                var filterGA = new GERENCIAS_ADMINISTRATIVAS_FILTER();
                var delegatesGA = filterGA.GetExpression(entityGA);
                List<GERENCIAS_ADMINISTRATIVAS> lov_ga = context.GERENCIAS_ADMINISTRATIVAS.Where(delegatesGA).ToList();
                if (lov_ga.Count > 0) { precDto.DESC_GA = lov_ga.FirstOrDefault().DESC_GA; }
                // Descripcion de Fuente
                var entityFUENTES = new FUENTES_FINANCIAMIENTO();
                entityFUENTES.FUENTE = prec.FUENTE;
                var filterFUENTE = new FUENTES_FINANCIAMIENTO_FILTER();
                var delegatesFUENTE = filterFUENTE.GetExpression(entityFUENTES);
                List<FUENTES_FINANCIAMIENTO> lov_fuente = context.FUENTES_FINANCIAMIENTO.Where(delegatesFUENTE).ToList();
                if (lov_fuente.Count > 0) { precDto.DESC_FUENTE = lov_fuente.FirstOrDefault().DESC_FUENTE; }
            }
        }
    }
}
