//------------------------------------------------------------------------------
//                         Secretaria de Finanzas
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using PAG_DA;
using PAG_DTO;
using PAG_INTERFACES;
using PAG_MAPPERS;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Linq;
using System.ServiceModel;
using System.Transactions;

namespace PAG_WCF
{
    
    
    public class DTP_TIPOS_PROGRA_DET_RDN
    {

        public List<DTP_TIPOS_PROGRA_DET_DTO> DTP_TIPOS_PROGRA_DET_listado()
        {
            // TODO: Desarrolle su Codigo Aqui.
            List<DTP_TIPOS_PROGRA_DET_DTO> ltDTP_TIPOS_PROGRA_DET = new List<DTP_TIPOS_PROGRA_DET_DTO>();
            //try
            //{
                using (PAG_Entities context = new PAG_Entities(PAG_Security.DictionaryClaims))
                {
                    IQueryable<DTP_TIPOS_PROGRA_DET> query;
                    query = from rec in context.DTP_TIPOS_PROGRA_DET
                            select rec;
                    foreach (var item in query)
                    {
                        var prec = item.ToDto();
                        obtenerDescripciones(ref prec);
                        ltDTP_TIPOS_PROGRA_DET.Add(prec);
                    }
                }
            //}
            //catch (Exception Ex)
            //{
            //    throw new FaultException(PAG_ServicesUtil.ErrorPAGDescDefecto, new FaultCode(PAG_ServicesUtil.ErrorPAGCodDefecto), Ex.InnerException.InnerException.Message);
            //}
            return ltDTP_TIPOS_PROGRA_DET;
        }

        public List<DTP_TIPOS_PROGRA_DET_DTO> DTP_TIPOS_PROGRA_DET_filtrado(DTP_TIPOS_PROGRA_DET_DTO precDto)
        {
            // TODO: Desarrolle su Codigo Aqui.
            List<DTP_TIPOS_PROGRA_DET_DTO> ltDTP_TIPOS_PROGRA_DET = new List<DTP_TIPOS_PROGRA_DET_DTO>();
            //try
            //{
                using (PAG_Entities context = new PAG_Entities(PAG_Security.DictionaryClaims))
                {
                    var entity = precDto.ToEntity();
                    var filters = new DTP_TIPOS_PROGRA_DET_FILTER();
                    var delegates = filters.GetExpression(entity);
                    //Aplicar pFilters Dinamico
                    if (!filters.hasFilters) { return ltDTP_TIPOS_PROGRA_DET; };
                    var filteredCollection = context.DTP_TIPOS_PROGRA_DET.Where(delegates).ToList();
                    //Transformar pFilter Dinamico
                    foreach (var item in filteredCollection)
                    {
                        var prec = item.ToDto();
                        obtenerDescripciones(ref prec);
                        ltDTP_TIPOS_PROGRA_DET.Add(prec);
                    }
                }
            //}
            //catch (Exception Ex)
            //{
            //    throw new FaultException(PAG_ServicesUtil.ErrorPAGDescDefecto, new FaultCode(PAG_ServicesUtil.ErrorPAGCodDefecto), Ex.InnerException.InnerException.Message);
            //}
            return ltDTP_TIPOS_PROGRA_DET;
        }

        public DTP_TIPOS_PROGRA_DET_DTO DTP_TIPOS_PROGRA_DET_inserta(DTP_TIPOS_PROGRA_DET_DTO precDto)
        {
            // TODO: Desarrolle su Codigo Aqui.
            //short max = 0;
            using (PAG_Entities context = new PAG_Entities(PAG_Security.DictionaryClaims))
            {
                precDto.API_ESTADO = "INICIAL";
                precDto.API_TRANSACCION = "CREAR";
                precDto.USU_CRE = PAG_ServicesUtil.usuarioPAG;
                //Insert NewRow Client
                DTP_TIPOS_PROGRA_DET entity = new DTP_TIPOS_PROGRA_DET();
                //Begin SavePoint
                using (TransactionScope SavePoint = new TransactionScope())
                {
                    entity = precDto.ToEntity();
                    context.DTP_TIPOS_PROGRA_DET.Add(entity);
                    context.SaveChanges();
                    SavePoint.Complete(); //Commit SavePoint
                    //IQueryable<DTP_TIPOS_PROGRA_DET> query;
                    //query = from rec in context.DTP_TIPOS_PROGRA_DET
                    //        select rec;
                    //max = query.Max(ultimo => ultimo.TIPO_PROGRAMACION);
                }//End SavePoint
                //Retuning NewRow DataBase
                precDto.GESTION = entity.GESTION;
                precDto.INSTITUCION = entity.INSTITUCION;
                precDto.GA = entity.GA;
                precDto.NRO_DOCUMENTO = entity.NRO_DOCUMENTO;
                precDto.INSTITUCION_PROG = entity.INSTITUCION_PROG;
                precDto.TIPO_PROGRAMACION = entity.TIPO_PROGRAMACION;
                //Retuning NewAudit DataBase
                precDto.API_ESTADO = entity.API_ESTADO;
                precDto.API_TRANSACCION = entity.API_TRANSACCION;
                precDto.USU_CRE = entity.USU_CRE;
                precDto.FEC_CRE = entity.FEC_CRE;
                precDto.USU_MOD = null;
                precDto.FEC_MOD = null;
            }
            //
            return precDto;
        }

        public DTP_TIPOS_PROGRA_DET_DTO DTP_TIPOS_PROGRA_DET_actualiza(DTP_TIPOS_PROGRA_DET_DTO precDto)
        {
            // TODO: Desarrolle su Codigo Aqui.
            using (PAG_Entities context = new PAG_Entities(PAG_Security.DictionaryClaims))
            {
                //Update NewRow Cliente
                //try
                //{
                    var entity = context.DTP_TIPOS_PROGRA_DET.Find(precDto.GESTION, precDto.INSTITUCION, precDto.GA, precDto.NRO_DOCUMENTO, precDto.INSTITUCION_PROG, precDto.GA_PROG, precDto.TIPO_PROGRAMACION);
                    if (entity == null) { throw new FaultException(PAG_ServicesUtil.ObtDescWFCExcepcion("PAG", 2, soloMensaje: true), new FaultCode(PAG_ServicesUtil.ObtCodWFCExcepcion("PAG", 2))); } /*"Registro NO Encontrado."*/
                    List<API_TRANSICIONES> transicion = context.API_TRANSICIONES.Where(col => col.TABLA == "DTP_TIPOS_PROGRA_DET" && col.ESTADO_INICIAL == entity.API_ESTADO && col.TRANSACCION == precDto.API_TRANSACCION).ToList();
                    if (transicion.Count == 0) { throw new FaultException(PAG_ServicesUtil.ObtDescWFCExcepcion("PAG", 4, soloMensaje: true), new FaultCode(PAG_ServicesUtil.ObtCodWFCExcepcion("PAG", 4))); } /*"Transición NO Definida en Flujo del Registro."*/
                                                                                                                                                                                                              //Assign Data NewRow
                    var pEntity = precDto.ToEntity();
                    entity.DESC_TIPO_PROGRAMACION = pEntity.DESC_TIPO_PROGRAMACION;
                    entity.ESPECIAL = pEntity.ESPECIAL;
                    entity.API_TRANSACCION = pEntity.API_TRANSACCION;
                    entity.USU_MOD = PAG_ServicesUtil.usuarioPAG;
                    //Begin SavePoint
                    using (TransactionScope SavePoint = new TransactionScope())
                    {
                        context.DTP_TIPOS_PROGRA_DET.Attach(entity);
                        var entry = context.Entry(entity);
                        entry.State = EntityState.Modified;
                        context.SaveChanges();
                        context.Entry(entity).Reload();
                        SavePoint.Complete(); //Commit SavePoint
                    }//End SavePoint
                    precDto.API_ESTADO = entity.API_ESTADO;
                    precDto.API_TRANSACCION = entity.API_TRANSACCION;
                    precDto.USU_MOD = entity.USU_MOD;
                    precDto.FEC_MOD = entity.FEC_MOD;
                //}
                //catch (Exception ex)
                //{
                //    if (PAG_ServicesUtil.EsErrorORA(ex))
                //    { throw new FaultException(PAG_ServicesUtil.ObtDescExcepcion(ex, soloMensaje: true), new FaultCode(PAG_ServicesUtil.ObtCodExcepcion(ex))); };
                //    throw new FaultException(PAG_ServicesUtil.ErrorPAGDescDefecto, new FaultCode(PAG_ServicesUtil.ErrorPAGCodDefecto), ex.InnerException.Message);
                //}
                //Retuning NewAudit DataBase
                
            }
            return precDto;
        }

        public DTP_TIPOS_PROGRA_DET_DTO DTP_TIPOS_PROGRA_DET_elimina(params object[] pkeysDto)
        {
            // TODO: Desarrolle su Codigo Aqui.
            throw new FaultException("PAG-00001 Implementada en Base de Datos.", new FaultCode("PAG-00001"));
        }
        public void DTP_TIPOS_PROGRA_DET_borrar(DTP_TIPOS_PROGRA_DET_DTO precDto)
        {
            using (PAG_Entities context = new PAG_Entities(PAG_Security.DictionaryClaims))
            {
                var entity = new DTP_TIPOS_PROGRA_DET();
                //try
                //{
                    //Begin SavePoint
                    using (TransactionScope SavePoint = new TransactionScope())
                    {
                        entity = context.DTP_TIPOS_PROGRA_DET.Find(precDto.GESTION, precDto.INSTITUCION, precDto.GA, precDto.NRO_DOCUMENTO,
                                                                   precDto.INSTITUCION_PROG, precDto.GA_PROG, precDto.TIPO_PROGRAMACION);
                        context.DTP_TIPOS_PROGRA_DET.Remove(entity);
                        context.SaveChanges();
                        SavePoint.Complete(); //Commit SavePoint
                    }//End SavePoint
                //}
                //catch (Exception ex)
                //{
                //    if (PAG_ServicesUtil.EsErrorORA(ex))
                //    { throw new FaultException(PAG_ServicesUtil.ObtDescExcepcion(ex, soloMensaje: true), new FaultCode(PAG_ServicesUtil.ObtCodExcepcion(ex))); };
                //    throw new FaultException(PAG_ServicesUtil.ErrorPAGDescDefecto, new FaultCode(PAG_ServicesUtil.ErrorPAGCodDefecto), ex.InnerException.Message);
                //}
            }
        }

        private void obtenerDescripciones(ref DTP_TIPOS_PROGRA_DET_DTO precDto)
        {
            using (PAG_Entities context = new PAG_Entities(PAG_Security.DictionaryClaims))
            {
                var prec = precDto;
                // Descripción de institución
                List<INSTITUCIONES> lov_ins = context.INSTITUCIONES.Where(col => col.INSTITUCION == prec.INSTITUCION).ToList();
                if (lov_ins.Count > 0) { precDto.DESC_INSTITUCION_PROG = lov_ins.FirstOrDefault().DESC_INSTITUCION; }
                // Descripción de GA
                var entityGA = new GERENCIAS_ADMINISTRATIVAS();
                entityGA.GESTION = prec.GESTION;
                entityGA.INSTITUCION = prec.INSTITUCION;
                entityGA.GA = prec.GA;
                var filterGA = new GERENCIAS_ADMINISTRATIVAS_FILTER();
                var delegatesGA = filterGA.GetExpression(entityGA);
                List<GERENCIAS_ADMINISTRATIVAS> lov_ga = context.GERENCIAS_ADMINISTRATIVAS.Where(delegatesGA).ToList();
                if (lov_ga.Count > 0) { precDto.DESC_GA_PROG = lov_ga.FirstOrDefault().DESC_GA; }
            }
        }

        public List<DTP_TIPOS_PROGRA_DET_DTO> DTP_TIPOS_PROGRA_DET_insertaArreglo(List<DTP_TIPOS_PROGRA_DET_DTO> precDto)
        {
            // TODO: Desarrolle su Codigo Aqui.
            using (PAG_Entities context = new PAG_Entities(PAG_Security.DictionaryClaims))
            {

                //Begin SavePoint
                using (TransactionScope SavePoint = new TransactionScope())
                {
                    foreach (var item in precDto)
                    {

                        item.API_ESTADO = "INICIAL";
                        item.API_TRANSACCION = "CREAR";
                        item.USU_CRE = PAG_ServicesUtil.usuarioPAG;
                        //Insert NewRow Client
                        DTP_TIPOS_PROGRA_DET entity = new DTP_TIPOS_PROGRA_DET();
                        entity = item.ToEntity();
                        context.DTP_TIPOS_PROGRA_DET.Add(entity);
                        //Retuning NewAudit DataBase
                        item.API_ESTADO = entity.API_ESTADO;
                        item.API_TRANSACCION = entity.API_TRANSACCION;
                        item.USU_CRE = entity.USU_CRE;
                        item.FEC_CRE = entity.FEC_CRE;
                        item.USU_MOD = null;
                        item.FEC_MOD = null;
                    }
                    context.SaveChanges();
                    SavePoint.Complete(); //Commit SavePoint
                }//End SavePoint

            }
            //
            return precDto;
        }

    }
}
