//------------------------------------------------------------------------------
//                         Secretaria de Finanzas
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using PAG_DA;
using PAG_DTO;
using PAG_INTERFACES;
using PAG_MAPPERS;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Linq;
using System.ServiceModel;
using System.Transactions;



namespace PAG_WCF
{
    
    
    public class TPR_DETALLES_RDN
    {

        public List<TPR_DETALLES_DTO> TPR_DETALLES_listado()
        {
            // TODO: Desarrolle su Codigo Aqui.
            List<TPR_DETALLES_DTO> ltTPR_DETALLES = new List<TPR_DETALLES_DTO>();
            //try
            //{
                using (PAG_Entities context = new PAG_Entities(PAG_Security.DictionaryClaims))
                {
                    IQueryable<TPR_DETALLES> query;
                    query = from rec in context.TPR_DETALLES
                            select rec;
                    foreach (var item in query)
                    {
                        var prec = item.ToDto();
                        obtenerDescripciones(ref prec);
                        ltTPR_DETALLES.Add(prec);
                    }
                }
            //}
            //catch (Exception Ex)
            //{
            //    throw new FaultException(PAG_ServicesUtil.ErrorPAGDescDefecto, new FaultCode(PAG_ServicesUtil.ErrorPAGCodDefecto), Ex.InnerException.InnerException.Message);
            //}
            return ltTPR_DETALLES;
        }

        public List<TPR_DETALLES_DTO> TPR_DETALLES_filtrado(TPR_DETALLES_DTO precDto)
        {
            // TODO: Desarrolle su Codigo Aqui.
            List<TPR_DETALLES_DTO> ltTPR_DETALLES = new List<TPR_DETALLES_DTO>();
            //try
            //{
                using (PAG_Entities context = new PAG_Entities(PAG_Security.DictionaryClaims))
                {
                    var entity = precDto.ToEntity();
                    var filters = new TPR_DETALLES_FILTER();
                    var delegates = filters.GetExpression(entity);
                    //Aplicar pFilters Dinamico
                    if (!filters.hasFilters) { return ltTPR_DETALLES; };
                    var filteredCollection = context.TPR_DETALLES.Where(delegates).ToList();
                    //Transformar pFilter Dinamico
                    foreach (var item in filteredCollection) {
                        var prec = item.ToDto();
                        obtenerDescripciones(ref prec);
                        ltTPR_DETALLES.Add(prec);

                    }
                }
            //}
            //catch (Exception Ex)
            //{
            //    throw new FaultException(PAG_ServicesUtil.ErrorPAGDescDefecto, new FaultCode(PAG_ServicesUtil.ErrorPAGCodDefecto), Ex.InnerException.InnerException.Message);
            //}
            return ltTPR_DETALLES;
        }

        public TPR_DETALLES_DTO TPR_DETALLES_inserta(TPR_DETALLES_DTO precDto)
        {
            using (PAG_Entities context = new PAG_Entities(PAG_Security.DictionaryClaims))
            {
                // TODO: Desarrolle su Codigo Aqui.
                precDto.API_ESTADO = "INICIAL";
                precDto.API_TRANSACCION = "CREAR";
                precDto.USU_CRE = PAG_ServicesUtil.usuarioPAG;
                //Insert NewRow Client
                TPR_DETALLES entity = new TPR_DETALLES();
                //try
                //{
                    //Begin SavePoint
                    using (TransactionScope SavePoint = new TransactionScope())
                    {
                        entity = precDto.ToEntity();
                        context.TPR_DETALLES.Add(entity);
                        context.SaveChanges();
                        SavePoint.Complete(); //Commit SavePoint
                    }//End SavePoint
                //}
                //catch (Exception ex)
                //{
                //    if (PAG_ServicesUtil.EsErrorORA(ex))
                //    { throw new FaultException(PAG_ServicesUtil.ObtDescExcepcion(ex, soloMensaje: true), new FaultCode(PAG_ServicesUtil.ObtCodExcepcion(ex))); };
                //    throw new FaultException(PAG_ServicesUtil.ErrorPAGDescDefecto, new FaultCode(PAG_ServicesUtil.ErrorPAGCodDefecto), ex.InnerException.Message);
                //}
                //Retuning NewRow DataBase
                precDto.INSTITUCION = entity.INSTITUCION;
                precDto.TIPO_PROGRAMACION = entity.TIPO_PROGRAMACION;
                precDto.SECUENCIA_DOC = entity.SECUENCIA_DOC;
                precDto.SECUENCIA_DET = entity.SECUENCIA_DET;
                precDto.GESTION = entity.GESTION;
                //Retuning NewAudit DataBase
                precDto.API_ESTADO = entity.API_ESTADO;
                precDto.API_TRANSACCION = entity.API_TRANSACCION;
                precDto.USU_CRE = entity.USU_CRE;
                precDto.FEC_CRE = entity.FEC_CRE;
                precDto.USU_MOD = null;
                precDto.FEC_MOD = null;
            }
            //
            return precDto;
        }

        public TPR_DETALLES_DTO TPR_DETALLES_actualiza(TPR_DETALLES_DTO precDto)
        {
            // TODO: Desarrolle su Codigo Aqui.
            using (PAG_Entities context = new PAG_Entities(PAG_Security.DictionaryClaims))
            {
                //Validate RDN
                var entity = context.TPR_DETALLES.Find(precDto.INSTITUCION, precDto.TIPO_PROGRAMACION, precDto.SECUENCIA_DOC, precDto.SECUENCIA_DET);
                if (entity == null) { throw new FaultException(PAG_ServicesUtil.ObtDescWFCExcepcion("PAG", 2, soloMensaje: true), new FaultCode(PAG_ServicesUtil.ObtCodWFCExcepcion("PAG", 2))); } /*"Registro NO Encontrado."*/
                List<API_TRANSICIONES> transicion = context.API_TRANSICIONES.Where(col => col.TABLA == "TPR_DETALLES" && col.ESTADO_INICIAL == entity.API_ESTADO && col.TRANSACCION == precDto.API_TRANSACCION).ToList();
                if (transicion.Count == 0) { throw new FaultException(PAG_ServicesUtil.ObtDescWFCExcepcion("PAG", 4, soloMensaje: true), new FaultCode(PAG_ServicesUtil.ObtCodWFCExcepcion("PAG", 4))); } /*"Transición NO Definida en Flujo del Registro."*/
                //Assign Data NewRow
                var pEntity = precDto.ToEntity();
                entity.GESTION = pEntity.GESTION;
                entity.ID_DOCUMENTO = pEntity.ID_DOCUMENTO;
                entity.ID_COLUMNA = pEntity.ID_COLUMNA;
                entity.VALOR_NUMERO = pEntity.VALOR_NUMERO;
                entity.VALOR_CADENA = pEntity.VALOR_CADENA;
                entity.API_TRANSACCION = pEntity.API_TRANSACCION;
                entity.USU_MOD = PAG_ServicesUtil.usuarioPAG;
                //Update NewRow Cliente
                //try
                //{
                    //Begin SavePoint
                    using (TransactionScope SavePoint = new TransactionScope())
                    {
                        context.TPR_DETALLES.Attach(entity);
                        var entry = context.Entry(entity);
                        entry.State = EntityState.Modified;
                        context.SaveChanges();
                        context.Entry(entity).Reload();
                        SavePoint.Complete(); //Commit SavePoint
                    }//End SavePoint
                //}
                //catch (Exception ex)
                //{
                //    if (PAG_ServicesUtil.EsErrorORA(ex))
                //    { throw new FaultException(PAG_ServicesUtil.ObtDescExcepcion(ex, soloMensaje: true), new FaultCode(PAG_ServicesUtil.ObtCodExcepcion(ex))); };
                //    throw new FaultException(PAG_ServicesUtil.ErrorPAGDescDefecto, new FaultCode(PAG_ServicesUtil.ErrorPAGCodDefecto), ex.InnerException.Message);
                //}
                //Retuning NewAudit DataBase
                precDto.API_ESTADO = entity.API_ESTADO;
                precDto.API_TRANSACCION = entity.API_TRANSACCION;
                precDto.USU_MOD = entity.USU_MOD;
                precDto.FEC_MOD = entity.FEC_MOD;
            }
            return precDto;
        }

        public TPR_DETALLES_DTO TPR_DETALLES_elimina(params object[] pkeysDto)
        {
            // TODO: Desarrolle su Codigo Aqui.
            throw new FaultException("PAG-00001 Implementada en Base de Datos.", new FaultCode("PAG-00001"));
        }
        private void obtenerDescripciones(ref TPR_DETALLES_DTO precDto)
        {
            using (PAG_Entities context = new PAG_Entities(PAG_Security.DictionaryClaims))
            {
                var prec = precDto;
                // Valores de columna
                List<DCO_COLUMNAS> lov_cols = context.DCO_COLUMNAS.Where(col => col.ID_COLUMNA == prec.ID_COLUMNA).ToList();
                if (lov_cols.Count > 0)
                {
                    precDto.DESC_COLUMNA = lov_cols.FirstOrDefault().DESC_COLUMNA;
                    precDto.TIPO_COLUMNA = lov_cols.FirstOrDefault().TIPO_COLUMNA;
                }
                // Valores de columna
                List<DCO_DOCUMENTOS> lov_docs = context.DCO_DOCUMENTOS.Where(col => col.ID_DOCUMENTO == prec.ID_DOCUMENTO).ToList();
                if (lov_docs.Count > 0)
                {
                    precDto.DESC_DOCUMENTO = lov_docs.FirstOrDefault().DESC_DOCUMENTO;
                }
            }
        }
    }
}
