//------------------------------------------------------------------------------
//                         Secretaria de Finanzas
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using PAG_DA;
using PAG_DTO;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


namespace PAG_MAPPERS
{
    
    
    public static class DLB_LIB_BOLSON_DET_MAPPERS
    {
        
        public static DLB_LIB_BOLSON_DET_DTO ToDto(this DLB_LIB_BOLSON_DET entity)
        {
            DLB_LIB_BOLSON_DET_DTO dto = new DLB_LIB_BOLSON_DET_DTO();
            dto.GESTION = entity.GESTION;
            dto.INSTITUCION = entity.INSTITUCION;
            dto.GA = entity.GA;
            dto.NRO_DOCUMENTO = entity.NRO_DOCUMENTO;
            dto.SECUENCIA = entity.SECUENCIA;
            dto.PAG_INSTITUCION = entity.PAG_INSTITUCION;
            dto.PAG_GA = entity.PAG_GA;
            dto.LIB_GESTION = entity.LIB_GESTION;
            dto.LIB_BANCO = entity.LIB_BANCO;
            dto.LIB_CUENTA = entity.LIB_CUENTA;
            dto.LIB_LIBRETA = entity.LIB_LIBRETA;
            dto.MONEDA = entity.MONEDA;
            dto.FUENTE = entity.FUENTE;
            dto.API_ESTADO = entity.API_ESTADO;
            dto.API_TRANSACCION = entity.API_TRANSACCION;
            dto.USU_CRE = entity.USU_CRE;
            dto.FEC_CRE = entity.FEC_CRE;
            dto.USU_MOD = entity.USU_MOD;
            dto.FEC_MOD = entity.FEC_MOD;
            return dto;
        }
        
        public static DLB_LIB_BOLSON_DET ToEntity(this DLB_LIB_BOLSON_DET_DTO dto)
        {
            DLB_LIB_BOLSON_DET entity = new DLB_LIB_BOLSON_DET();
            entity.GESTION = dto.GESTION;
            entity.INSTITUCION = dto.INSTITUCION;
            entity.GA = dto.GA;
            entity.NRO_DOCUMENTO = dto.NRO_DOCUMENTO;
            entity.SECUENCIA = dto.SECUENCIA;
            entity.PAG_INSTITUCION = dto.PAG_INSTITUCION;
            entity.PAG_GA = dto.PAG_GA;
            entity.LIB_GESTION = dto.LIB_GESTION;
            entity.LIB_BANCO = dto.LIB_BANCO;
            entity.LIB_CUENTA = dto.LIB_CUENTA;
            entity.LIB_LIBRETA = dto.LIB_LIBRETA;
            entity.MONEDA = dto.MONEDA;
            entity.FUENTE = dto.FUENTE;
            entity.API_ESTADO = dto.API_ESTADO;
            entity.API_TRANSACCION = dto.API_TRANSACCION;
            entity.USU_CRE = dto.USU_CRE;
            entity.FEC_CRE = dto.FEC_CRE;
            entity.USU_MOD = dto.USU_MOD;
            entity.FEC_MOD = dto.FEC_MOD;
            return entity;
        }
    }
}
