//------------------------------------------------------------------------------
//                         Secretaria de Finanzas
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using PAG_DA;
using PAG_DTO;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


namespace PAG_MAPPERS
{
    
    
    public static class DTP_TIPOS_PROGRA_DET_MAPPERS
    {
        
        public static DTP_TIPOS_PROGRA_DET_DTO ToDto(this DTP_TIPOS_PROGRA_DET entity)
        {
            DTP_TIPOS_PROGRA_DET_DTO dto = new DTP_TIPOS_PROGRA_DET_DTO();
            dto.GESTION = entity.GESTION;
            dto.INSTITUCION = entity.INSTITUCION;
            dto.GA = entity.GA;
            dto.NRO_DOCUMENTO = entity.NRO_DOCUMENTO;
            dto.INSTITUCION_PROG = entity.INSTITUCION_PROG;
            dto.GA_PROG = entity.GA_PROG;
            dto.TIPO_PROGRAMACION = entity.TIPO_PROGRAMACION;
            dto.DESC_TIPO_PROGRAMACION = entity.DESC_TIPO_PROGRAMACION;
            dto.ESPECIAL = entity.ESPECIAL;
            dto.API_ESTADO = entity.API_ESTADO;
            dto.API_TRANSACCION = entity.API_TRANSACCION;
            dto.USU_CRE = entity.USU_CRE;
            dto.FEC_CRE = entity.FEC_CRE;
            dto.USU_MOD = entity.USU_MOD;
            dto.FEC_MOD = entity.FEC_MOD;
            return dto;
        }
        
        public static DTP_TIPOS_PROGRA_DET ToEntity(this DTP_TIPOS_PROGRA_DET_DTO dto)
        {
            DTP_TIPOS_PROGRA_DET entity = new DTP_TIPOS_PROGRA_DET();
            entity.GESTION = dto.GESTION;
            entity.INSTITUCION = dto.INSTITUCION;
            entity.GA = dto.GA;
            entity.NRO_DOCUMENTO = dto.NRO_DOCUMENTO;
            entity.INSTITUCION_PROG = dto.INSTITUCION_PROG;
            entity.GA_PROG = dto.GA_PROG;
            entity.TIPO_PROGRAMACION = dto.TIPO_PROGRAMACION;
            entity.DESC_TIPO_PROGRAMACION = dto.DESC_TIPO_PROGRAMACION;
            entity.ESPECIAL = dto.ESPECIAL;
            entity.API_ESTADO = dto.API_ESTADO;
            entity.API_TRANSACCION = dto.API_TRANSACCION;
            entity.USU_CRE = dto.USU_CRE;
            entity.FEC_CRE = dto.FEC_CRE;
            entity.USU_MOD = dto.USU_MOD;
            entity.FEC_MOD = dto.FEC_MOD;
            return entity;
        }
    }
}
