//------------------------------------------------------------------------------
//                         Secretaria de Finanzas
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using PAG_DA;
using PAG_DTO;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


namespace PAG_MAPPERS
{
    
    
    public static class PRG_LIBRETAS_BOLSON_MAPPERS
    {
        
        public static PRG_LIBRETAS_BOLSON_DTO ToDto(this PRG_LIBRETAS_BOLSON entity)
        {
            PRG_LIBRETAS_BOLSON_DTO dto = new PRG_LIBRETAS_BOLSON_DTO();
            dto.GESTION = entity.GESTION;
            dto.INSTITUCION = entity.INSTITUCION;
            dto.GA = entity.GA;
            dto.BANCO = entity.BANCO;
            dto.CUENTA = entity.CUENTA;
            dto.LIBRETA = entity.LIBRETA;
            dto.MONEDA = entity.MONEDA;
            dto.FUENTE = entity.FUENTE;
            dto.API_ESTADO = entity.API_ESTADO;
            dto.API_TRANSACCION = entity.API_TRANSACCION;
            dto.USU_CRE = entity.USU_CRE;
            dto.FEC_CRE = entity.FEC_CRE;
            dto.USU_MOD = entity.USU_MOD;
            dto.FEC_MOD = entity.FEC_MOD;
            return dto;
        }
        
        public static PRG_LIBRETAS_BOLSON ToEntity(this PRG_LIBRETAS_BOLSON_DTO dto)
        {
            PRG_LIBRETAS_BOLSON entity = new PRG_LIBRETAS_BOLSON();
            entity.GESTION = dto.GESTION;
            entity.INSTITUCION = dto.INSTITUCION;
            entity.GA = dto.GA;
            entity.BANCO = dto.BANCO;
            entity.CUENTA = dto.CUENTA;
            entity.LIBRETA = dto.LIBRETA;
            entity.MONEDA = dto.MONEDA;
            entity.FUENTE = dto.FUENTE;
            entity.API_ESTADO = dto.API_ESTADO;
            entity.API_TRANSACCION = dto.API_TRANSACCION;
            entity.USU_CRE = dto.USU_CRE;
            entity.FEC_CRE = dto.FEC_CRE;
            entity.USU_MOD = dto.USU_MOD;
            entity.FEC_MOD = dto.FEC_MOD;
            return entity;
        }
    }
}
