//------------------------------------------------------------------------------
//                         Secretaria de Finanzas
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using PAG_DA;
using PAG_DTO;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


namespace PAG_MAPPERS
{
    
    
    public static class TPR_TIPOS_PROGRAMACION_MAPPERS
    {
        
        public static TPR_TIPOS_PROGRAMACION_DTO ToDto(this TPR_TIPOS_PROGRAMACION entity)
        {
            TPR_TIPOS_PROGRAMACION_DTO dto = new TPR_TIPOS_PROGRAMACION_DTO();
            dto.INSTITUCION = entity.INSTITUCION;
            dto.GA = entity.GA;
            dto.TIPO_PROGRAMACION = entity.TIPO_PROGRAMACION;
            dto.API_ESTADO = entity.API_ESTADO;
            dto.API_TRANSACCION = entity.API_TRANSACCION;
            dto.DESC_TIPO_PROGRAMACION = entity.DESC_TIPO_PROGRAMACION;
            dto.ESPECIAL = entity.ESPECIAL;
            dto.FEC_CRE = entity.FEC_CRE;
            dto.FEC_MOD = entity.FEC_MOD;
            dto.USU_CRE = entity.USU_CRE;
            dto.USU_MOD = entity.USU_MOD;        
            return dto;
        }
        
        public static TPR_TIPOS_PROGRAMACION ToEntity(this TPR_TIPOS_PROGRAMACION_DTO dto)
        {
            TPR_TIPOS_PROGRAMACION entity = new TPR_TIPOS_PROGRAMACION();
            entity.INSTITUCION = dto.INSTITUCION;
            entity.GA = dto.GA;
            entity.TIPO_PROGRAMACION = dto.TIPO_PROGRAMACION;
            entity.API_ESTADO = dto.API_ESTADO;
            entity.API_TRANSACCION = dto.API_TRANSACCION;
            entity.DESC_TIPO_PROGRAMACION = dto.DESC_TIPO_PROGRAMACION;
            entity.ESPECIAL = dto.ESPECIAL;
            entity.FEC_CRE = dto.FEC_CRE;
            entity.FEC_MOD = dto.FEC_MOD;
            entity.USU_CRE = dto.USU_CRE;
            entity.USU_MOD = dto.USU_MOD;
            return entity;
        }
    }
}
