//------------------------------------------------------------------------------
//                         Secretaria de Finanzas
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using PAG_DA;
using PAG_DTO;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


namespace PAG_MAPPERS
{
    
    
    public static class TPR_DETALLES_MAPPERS
    {
        
        public static TPR_DETALLES_DTO ToDto(this TPR_DETALLES entity)
        {
            TPR_DETALLES_DTO dto = new TPR_DETALLES_DTO();
            dto.INSTITUCION = entity.INSTITUCION;
            dto.GA = entity.GA;
            dto.TIPO_PROGRAMACION = entity.TIPO_PROGRAMACION;
            dto.SECUENCIA_DOC = entity.SECUENCIA_DOC;
            dto.SECUENCIA_DET = entity.SECUENCIA_DET;
            dto.GESTION = entity.GESTION;
            dto.ID_DOCUMENTO = entity.ID_DOCUMENTO;
            dto.ID_COLUMNA = entity.ID_COLUMNA;
            dto.VALOR_NUMERO = entity.VALOR_NUMERO;
            dto.VALOR_CADENA = entity.VALOR_CADENA;
            dto.API_ESTADO = entity.API_ESTADO;
            dto.API_TRANSACCION = entity.API_TRANSACCION;
            dto.USU_CRE = entity.USU_CRE;
            dto.FEC_CRE = entity.FEC_CRE;
            dto.USU_MOD = entity.USU_MOD;
            dto.FEC_MOD = entity.FEC_MOD;
            return dto;
        }
        
        public static TPR_DETALLES ToEntity(this TPR_DETALLES_DTO dto)
        {
            TPR_DETALLES entity = new TPR_DETALLES();
            entity.INSTITUCION = dto.INSTITUCION;
            entity.GA = dto.GA;
            entity.TIPO_PROGRAMACION = dto.TIPO_PROGRAMACION;
            entity.SECUENCIA_DOC = dto.SECUENCIA_DOC;
            entity.SECUENCIA_DET = dto.SECUENCIA_DET;
            entity.GESTION = dto.GESTION;
            entity.ID_DOCUMENTO = dto.ID_DOCUMENTO;
            entity.ID_COLUMNA = dto.ID_COLUMNA;
            entity.VALOR_NUMERO = dto.VALOR_NUMERO;
            entity.VALOR_CADENA = dto.VALOR_CADENA;
            entity.API_ESTADO = dto.API_ESTADO;
            entity.API_TRANSACCION = dto.API_TRANSACCION;
            entity.USU_CRE = dto.USU_CRE;
            entity.FEC_CRE = dto.FEC_CRE;
            entity.USU_MOD = dto.USU_MOD;
            entity.FEC_MOD = dto.FEC_MOD;
            return entity;
        }
    }
}
